In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('stock_exchange_data/indexData.csv')

In [3]:
df.head()

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

In [4]:
df.tail()

,Index,Date,Open,High,Low,Close,Adj Close,Volume
112452,N100,2021-05-27,1241.119995,1251.910034,1241.119995,1247.069946,1247.069946,379696400.0
112453,N100,2021-05-28,1249.469971,1259.209961,1249.030029,1256.599976,1256.599976,160773400.0
112454,N100,2021-05-31,1256.079956,1258.880005,1248.140015,1248.930054,1248.930054,91173700.0
112455,N100,2021-06-01,1254.609985,1265.660034,1254.609985,1258.579956,1258.579956,155179900.0
112456,N100,2021-06-02,1258.489990,1263.709961,1258.239990,1263.619995,1263.619995,148465000.0

In [5]:
df.index # return the actual index range

RangeIndex(start=0, stop=112457, step=1)

In [6]:
df.Index # return the index series

0          NYA
1          NYA
2          NYA
3          NYA
4          NYA
          ...
112452    N100
112453    N100
112454    N100
112455    N100
112456    N100
Name: Index, Length: 112457, dtype: object

In [7]:
df['Index']

0          NYA
1          NYA
2          NYA
3          NYA
4          NYA
          ...
112452    N100
112453    N100
112454    N100
112455    N100
112456    N100
Name: Index, Length: 112457, dtype: object

In [8]:
df['Index'][0]

'NYA'

## iloc

- Index-based Selection

    Both loc and iloc are row-first, column-second. This is the opposite of what we do in native Python, which is column-first, row-second.

    This means that it's marginally easier to retrieve rows, and marginally harder to get retrieve columns.

In [9]:
df.iloc[0] # retrieve the row at index 0

Index               NYA
Date         1965-12-31
Open         528.690002
High         528.690002
Low          528.690002
Close        528.690002
Adj Close    528.690002
Volume              0.0
Name: 0, dtype: object

In [10]:
df.iloc[:, 1] # retrieve all rows (all indexes), at column 1

0         1965-12-31
1         1966-01-03
2         1966-01-04
3         1966-01-05
4         1966-01-06
             ...
112452    2021-05-27
112453    2021-05-28
112454    2021-05-31
112455    2021-06-01
112456    2021-06-02
Name: Date, Length: 112457, dtype: object

In [11]:
df.iloc[:3, 1] # retrieve first 3 rows, at column 1

0    1965-12-31
1    1966-01-03
2    1966-01-04
Name: Date, dtype: object

In [12]:
df.iloc[[1, 2, 3, 4], 1] # retrieve all rows in the index list, at column 1

1    1966-01-03
2    1966-01-04
3    1966-01-05
4    1966-01-06
Name: Date, dtype: object

In [13]:
df.tail()

,Index,Date,Open,High,Low,Close,Adj Close,Volume
112452,N100,2021-05-27,1241.119995,1251.910034,1241.119995,1247.069946,1247.069946,379696400.0
112453,N100,2021-05-28,1249.469971,1259.209961,1249.030029,1256.599976,1256.599976,160773400.0
112454,N100,2021-05-31,1256.079956,1258.880005,1248.140015,1248.930054,1248.930054,91173700.0
112455,N100,2021-06-01,1254.609985,1265.660034,1254.609985,1258.579956,1258.579956,155179900.0
112456,N100,2021-06-02,1258.489990,1263.709961,1258.239990,1263.619995,1263.619995,148465000.0

In [14]:
df.iloc[-5:] # retrieve last 5 indexes, equivalent to tail()

,Index,Date,Open,High,Low,Close,Adj Close,Volume
112452,N100,2021-05-27,1241.119995,1251.910034,1241.119995,1247.069946,1247.069946,379696400.0
112453,N100,2021-05-28,1249.469971,1259.209961,1249.030029,1256.599976,1256.599976,160773400.0
112454,N100,2021-05-31,1256.079956,1258.880005,1248.140015,1248.930054,1248.930054,91173700.0
112455,N100,2021-06-01,1254.609985,1265.660034,1254.609985,1258.579956,1258.579956,155179900.0
112456,N100,2021-06-02,1258.489990,1263.709961,1258.239990,1263.619995,1263.619995,148465000.0

## loc

- Label-based selection

    The second paradigm for attribute selection is the one followed by the loc operator: label-based selection. In this paradigm, it's the data index value, not its position, which matters.

In [15]:
df.loc[:5, 'Date'] # retrieve first 6 rows, at 'Date' column

0    1965-12-31
1    1966-01-03
2    1966-01-04
3    1966-01-05
4    1966-01-06
5    1966-01-07
Name: Date, dtype: object

In [16]:
df.loc[-5:, ['Date', 'Open', 'Volume']] # this actually returns all rows because negative slicing is not supported in loc

              Date         Open       Volume
0       1965-12-31   528.690002          0.0
1       1966-01-03   527.210022          0.0
2       1966-01-04   527.840027          0.0
3       1966-01-05   531.119995          0.0
4       1966-01-06   532.070007          0.0
...            ...          ...          ...
112452  2021-05-27  1241.119995  379696400.0
112453  2021-05-28  1249.469971  160773400.0
112454  2021-05-31  1256.079956   91173700.0
112455  2021-06-01  1254.609985  155179900.0
112456  2021-06-02  1258.489990  148465000.0

[112457 rows x 3 columns]

## Choosing between loc and iloc

    When choosing or transitioning between loc and iloc, there is one "gotcha" worth keeping in mind, which is that the two methods use slightly different indexing schemes.

    iloc uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. So 0:10 will select entries 0,...,9. loc, meanwhile, indexes inclusively. So 0:10 will select entries 0,...,10.

    Why the change? Remember that loc can index any stdlib type: strings, for example. If we have a DataFrame with index values Apples, ..., Potatoes, ..., and we want to select "all the alphabetical fruit choices between Apples and Potatoes", then it's a lot more convenient to index df.loc['Apples':'Potatoes'] than it is to index something like df.loc['Apples', 'Potatoet'] (t coming after s in the alphabet).

    This is particularly confusing when the DataFrame index is a simple numerical list, e.g. 0,...,1000. In this case df.iloc[0:1000] will return 1000 entries, while df.loc[0:1000] return 1001 of them! To get 1000 elements using loc, you will need to go one lower and ask for df.loc[0:999].

    Otherwise, the semantics of using loc are the same as those for iloc.

In [17]:
sf = pd.DataFrame({'Stock':['Apple', 'Google', 'OpenAI', 'Celsius', 'TIKTAK', 'META', 'HNG', 'XKJ', 'Alani'], 'Price':[100, 320, 482, 883, 432, 399, 732, None, 883], 'Location':['USA', 'CAN', 'CHIL', 'UAE', 'KOR', 'SEB', 'CHI', 'JAP', 'PHI'], 'ETF':['Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y'], 'Valid': [None, None, None, None, None, None, None, None, None], 'Shares': [139, 421, 123, 93, 212, 194, 283, 333, 93]})

In [18]:
sf.set_index('Stock', inplace=True) # set index to 'Stock' column, modifying the original DataFrame index

In [19]:
sf.head() # Stock is the indexing column for the DataFrame

         Price Location ETF Valid  Shares
Stock
Apple    100.0      USA   Y  None     139
Google   320.0      CAN   Y  None     421
OpenAI   482.0     CHIL   N  None     123
Celsius  883.0      UAE   N  None      93
TIKTAK   432.0      KOR   Y  None     212

In [20]:
sf.loc['Google':'TIKTAK', ['Location', 'ETF', 'Shares']]  
# retrieve rows from 'Google' to 'TIKTAK', at 'Location' and 'ETF' columns

        Location ETF  Shares
Stock
Google       CAN   Y     421
OpenAI      CHIL   N     123
Celsius      UAE   N      93
TIKTAK       KOR   Y     212

In [21]:
sf.iloc[1:5, [1, 2, 4]]

        Location ETF  Shares
Stock
Google       CAN   Y     421
OpenAI      CHIL   N     123
Celsius      UAE   N      93
TIKTAK       KOR   Y     212

## Conditional Selection

In [22]:
sf.Price > 400  # boolean mask for rows where Price is greater than 400, return a series of True/False

Stock
Apple      False
Google     False
OpenAI      True
Celsius     True
TIKTAK      True
META       False
HNG         True
XKJ        False
Alani       True
Name: Price, dtype: bool

In [23]:
sf.loc[sf['Price'] > 400, :] 
# sf['Price'] > 400 is a series of True/False values indicating whether each row meets the condition, 
# if true the row is included in the result
# in the series of true/false values, if True, the corresponding row is included in the output DataFrame

         Price Location ETF Valid  Shares
Stock
OpenAI   482.0     CHIL   N  None     123
Celsius  883.0      UAE   N  None      93
TIKTAK   432.0      KOR   Y  None     212
HNG      732.0      CHI   Y  None     283
Alani    883.0      PHI   Y  None      93

In [24]:
sf.loc[(sf['Price'] > 300) & (sf['ETF'] == 'Y'), ['Location', 'Price', 'ETF']]
# retrieve rows where Price is greater than 300 and ETF is 'Y', at 'Location', 'Price', and 'ETF' columns
# the result this conditonal filtering is from two series of True/False values combined with the & operator

       Location  Price ETF
Stock
Google      CAN  320.0   Y
TIKTAK      KOR  432.0   Y
META        SEB  399.0   Y
HNG         CHI  732.0   Y
Alani       PHI  883.0   Y

In [25]:
sf['Price'] > 399

Stock
Apple      False
Google     False
OpenAI      True
Celsius     True
TIKTAK      True
META       False
HNG         True
XKJ        False
Alani       True
Name: Price, dtype: bool

In [26]:
sf.loc[sf['Price'] > 399, :]

         Price Location ETF Valid  Shares
Stock
OpenAI   482.0     CHIL   N  None     123
Celsius  883.0      UAE   N  None      93
TIKTAK   432.0      KOR   Y  None     212
HNG      732.0      CHI   Y  None     283
Alani    883.0      PHI   Y  None      93

In [27]:
sf[sf['Price'] > 399]
# shorthand version of the above loc method
# return a dataframe with only rows 
# where Price is greater than 399

         Price Location ETF Valid  Shares
Stock
OpenAI   482.0     CHIL   N  None     123
Celsius  883.0      UAE   N  None      93
TIKTAK   432.0      KOR   Y  None     212
HNG      732.0      CHI   Y  None     283
Alani    883.0      PHI   Y  None      93

In [28]:
sf.loc[sf['Location'].isin(['CHI', 'JAP', 'USA'])] 
# return a dataframe with rows where Location is either 'CHI', 'JAP', or 'USA'

       Price Location ETF Valid  Shares
Stock
Apple  100.0      USA   Y  None     139
HNG    732.0      CHI   Y  None     283
XKJ      NaN      JAP   N  None     333

In [29]:
sf.loc[sf.Price.notnull()]  # return a dataframe with rows where Price is not null

         Price Location ETF Valid  Shares
Stock
Apple    100.0      USA   Y  None     139
Google   320.0      CAN   Y  None     421
OpenAI   482.0     CHIL   N  None     123
Celsius  883.0      UAE   N  None      93
TIKTAK   432.0      KOR   Y  None     212
META     399.0      SEB   Y  None     194
HNG      732.0      CHI   Y  None     283
Alani    883.0      PHI   Y  None      93

## Markdown Notes:

    iloc vs loc

- iloc 'looking at the position at that index'
- loc 'looks up the index, look for a specific entry'

## Assign

In [30]:
sf['Valid'] = 67 # assign all rows in the series 'Valid' to 67

In [31]:
sf.loc[sf.index == 'Apple', 'Price'] = 1010 
# set the 'Price' for the row with index 'Apple' to 1010

In [32]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Apple    1010.0      USA   Y     67     139
Google    320.0      CAN   Y     67     421
OpenAI    482.0     CHIL   N     67     123
Celsius   883.0      UAE   N     67      93
TIKTAK    432.0      KOR   Y     67     212
META      399.0      SEB   Y     67     194
HNG       732.0      CHI   Y     67     283
XKJ         NaN      JAP   N     67     333
Alani     883.0      PHI   Y     67      93

In [33]:
sf.iloc[2:7, 0] # this is a series, return only price series

Stock
OpenAI     482.0
Celsius    883.0
TIKTAK     432.0
META       399.0
HNG        732.0
Name: Price, dtype: float64

In [34]:
sf.iloc[2:7, :1] # slices return a dataframe

         Price
Stock
OpenAI   482.0
Celsius  883.0
TIKTAK   432.0
META     399.0
HNG      732.0

In [35]:
sf.loc['OpenAI':'HNG', 'Valid'] = 9999 
# from 'OpenAI' to 'HNG' rows, assign the value 9999 to the 'Valid' column

In [36]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Apple    1010.0      USA   Y     67     139
Google    320.0      CAN   Y     67     421
OpenAI    482.0     CHIL   N   9999     123
Celsius   883.0      UAE   N   9999      93
TIKTAK    432.0      KOR   Y   9999     212
META      399.0      SEB   Y   9999     194
HNG       732.0      CHI   Y   9999     283
XKJ         NaN      JAP   N     67     333
Alani     883.0      PHI   Y     67      93

In [37]:
sf['Valid'] = range(sf.shape[0], 0, -1) 
# len(sf) or sf.shape[0] returns the number of rows in the DataFrame, 
# so this assigns a descending range of values to the 'Valid' column

In [38]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Apple    1010.0      USA   Y      9     139
Google    320.0      CAN   Y      8     421
OpenAI    482.0     CHIL   N      7     123
Celsius   883.0      UAE   N      6      93
TIKTAK    432.0      KOR   Y      5     212
META      399.0      SEB   Y      4     194
HNG       732.0      CHI   Y      3     283
XKJ         NaN      JAP   N      2     333
Alani     883.0      PHI   Y      1      93

In [39]:
sf.sort_values(by='Price', inplace=True)

In [40]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      8     421
META      399.0      SEB   Y      4     194
TIKTAK    432.0      KOR   Y      5     212
OpenAI    482.0     CHIL   N      7     123
HNG       732.0      CHI   Y      3     283
Celsius   883.0      UAE   N      6      93
Alani     883.0      PHI   Y      1      93
Apple    1010.0      USA   Y      9     139
XKJ         NaN      JAP   N      2     333

In [41]:
sf.sort_values(by='Valid').loc[:, ['Price', 'Valid']] 
# sort by 'Valid' column and return the 'Price' and 'Valid' column

          Price  Valid
Stock
Alani     883.0      1
XKJ         NaN      2
HNG       732.0      3
META      399.0      4
TIKTAK    432.0      5
Celsius   883.0      6
OpenAI    482.0      7
Google    320.0      8
Apple    1010.0      9

In [42]:
print(sf)

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      8     421
META      399.0      SEB   Y      4     194
TIKTAK    432.0      KOR   Y      5     212
OpenAI    482.0     CHIL   N      7     123
HNG       732.0      CHI   Y      3     283
Celsius   883.0      UAE   N      6      93
Alani     883.0      PHI   Y      1      93
Apple    1010.0      USA   Y      9     139
XKJ         NaN      JAP   N      2     333

In [43]:
max_price = sf['Price'] < 600
type = sf['ETF'].isin(['Y'])

sf.loc[max_price & type, :]

        Price Location ETF  Valid  Shares
Stock
Google  320.0      CAN   Y      8     421
META    399.0      SEB   Y      4     194
TIKTAK  432.0      KOR   Y      5     212

## Summary of Functions / Maps


        However, the data does not always come out of memory in the format we want it in right out of the bat. Sometimes we have to do some more work ourselves to reformat it for the task at hand. This tutorial will cover different operations we can apply to our data to get the input "just right".

In [44]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      8     421
META      399.0      SEB   Y      4     194
TIKTAK    432.0      KOR   Y      5     212
OpenAI    482.0     CHIL   N      7     123
HNG       732.0      CHI   Y      3     283
Celsius   883.0      UAE   N      6      93
Alani     883.0      PHI   Y      1      93
Apple    1010.0      USA   Y      9     139
XKJ         NaN      JAP   N      2     333

In [45]:
sf.describe() # returns a dataframe with statistical summary of all numeric columns

             Price     Valid      Shares
count     8.000000  9.000000    9.000000
mean    642.625000  5.000000  210.111111
std     265.145748  2.738613  114.688104
min     320.000000  1.000000   93.000000
25%     423.750000  3.000000  123.000000
50%     607.000000  5.000000  194.000000
75%     883.000000  7.000000  283.000000
max    1010.000000  9.000000  421.000000

In [46]:
sf.Price.describe() 
# returns a series with statistical summary of the 'Price' column

count       8.000000
mean      642.625000
std       265.145748
min       320.000000
25%       423.750000
50%       607.000000
75%       883.000000
max      1010.000000
Name: Price, dtype: float64

In [47]:
sf.Price.mean() # returns the mean of the 'Price' column

np.float64(642.625)

In [48]:
sf.Location.unique() # returns an array of unique values in the 'array' column

array(['CAN', 'SEB', 'KOR', 'CHIL', 'CHI', 'UAE', 'PHI', 'USA', 'JAP'],
      dtype=object)

In [49]:
sf.ETF.value_counts() # returns a series with counts of unique values in the 'ETF' column

ETF
Y    6
N    3
Name: count, dtype: int64

# **Pandas Testing**

In [50]:
sf.count() # count non-null entries for each column

Price       8
Location    9
ETF         9
Valid       9
Shares      9
dtype: int64

In [51]:
price_mean = sf.Price.mean() # returns the mean of the 'Price' column

print('Price Mean:', price_mean)

sf.Price.map(lambda x: x - price_mean) 
# return a series of the form (current index value - mean) for each index in the 'Price' column

Price Mean: 642.625

Stock
Google    -322.625
META      -243.625
TIKTAK    -210.625
OpenAI    -160.625
HNG         89.375
Celsius    240.375
Alani      240.375
Apple      367.375
XKJ            NaN
Name: Price, dtype: float64

In [52]:
import random

def randrow(row):
    row.Valid = random.randint(0, 10)
    return row

sf.apply(randrow, axis=1) # this does not modify the original DataFrame

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      8     421
META      399.0      SEB   Y     10     194
TIKTAK    432.0      KOR   Y      6     212
OpenAI    482.0     CHIL   N      8     123
HNG       732.0      CHI   Y      9     283
Celsius   883.0      UAE   N      5      93
Alani     883.0      PHI   Y      8      93
Apple    1010.0      USA   Y      4     139
XKJ         NaN      JAP   N      3     333

In [53]:
sf.sum(axis=0, numeric_only=False) 
# sum of all numeric columns and concatenates strings, 
# axis=0 means summing down the rows for each column

Price                             5141.0
Location    CANSEBKORCHILCHIUAEPHIUSAJAP
ETF                            YYYNYNYYN
Valid                                 45
Shares                              1891
dtype: object

In [54]:
sf

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      8     421
META      399.0      SEB   Y      4     194
TIKTAK    432.0      KOR   Y      5     212
OpenAI    482.0     CHIL   N      7     123
HNG       732.0      CHI   Y      3     283
Celsius   883.0      UAE   N      6      93
Alani     883.0      PHI   Y      1      93
Apple    1010.0      USA   Y      9     139
XKJ         NaN      JAP   N      2     333

In [55]:
sf.sum(axis=1, numeric_only=True) 
# sum of all numeric columns, axis=1 means summing across the columns for each row

Stock
Google      749.0
META        597.0
TIKTAK      649.0
OpenAI      612.0
HNG        1018.0
Celsius     982.0
Alani       977.0
Apple      1158.0
XKJ         335.0
dtype: float64

In [56]:
randrow(sf) # this modifies the original DataFrame 
# called with the whole DataFrame (row is the DataFrame)
# mutates sf in-place because you passed the DataFrame

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      7     421
META      399.0      SEB   Y      7     194
TIKTAK    432.0      KOR   Y      7     212
OpenAI    482.0     CHIL   N      7     123
HNG       732.0      CHI   Y      7     283
Celsius   883.0      UAE   N      7      93
Alani     883.0      PHI   Y      7      93
Apple    1010.0      USA   Y      7     139
XKJ         NaN      JAP   N      7     333

In [57]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      7     421
META      399.0      SEB   Y      7     194
TIKTAK    432.0      KOR   Y      7     212
OpenAI    482.0     CHIL   N      7     123
HNG       732.0      CHI   Y      7     283
Celsius   883.0      UAE   N      7      93
Alani     883.0      PHI   Y      7      93
Apple    1010.0      USA   Y      7     139
XKJ         NaN      JAP   N      7     333

In [58]:
sf.Valid = range(len(sf), 0, -1) # revert values back

In [59]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      9     421
META      399.0      SEB   Y      8     194
TIKTAK    432.0      KOR   Y      7     212
OpenAI    482.0     CHIL   N      6     123
HNG       732.0      CHI   Y      5     283
Celsius   883.0      UAE   N      4      93
Alani     883.0      PHI   Y      3      93
Apple    1010.0      USA   Y      2     139
XKJ         NaN      JAP   N      1     333

In [60]:
sf.Price - price_mean # built in mapping operation

Stock
Google    -322.625
META      -243.625
TIKTAK    -210.625
OpenAI    -160.625
HNG         89.375
Celsius    240.375
Alani      240.375
Apple      367.375
XKJ            NaN
Name: Price, dtype: float64

In [61]:
sf.Location + " - " + sf.ETF # concatenate strings from 'Location' and 'ETF' columns with " - " in between

Stock
Google      CAN - Y
META        SEB - Y
TIKTAK      KOR - Y
OpenAI     CHIL - N
HNG         CHI - Y
Celsius     UAE - N
Alani       PHI - Y
Apple       USA - Y
XKJ         JAP - N
dtype: object

In [62]:
sf.Price.median()

np.float64(607.0)

### Find Best Price to Share Ratio

In [63]:
price_to_share_ratio = sf.Price/sf.Shares # price to share ratio for each stock
print(price_to_share_ratio)

Stock
Google     0.760095
META       2.056701
TIKTAK     2.037736
OpenAI     3.918699
HNG        2.586572
Celsius    9.494624
Alani      9.494624
Apple      7.266187
XKJ             NaN
dtype: float64

In [64]:
highest_stock1 = sf.apply(lambda x: x.Price/x.Shares, axis=1).sort_values(ascending=False).index[0] 
# returns the index of the stock with the highest price to share ratio
print(highest_stock1)

Alani

In [65]:
highest_stock2 = price_to_share_ratio.idxmax() # returns the index of the maximum value in the series
print(highest_stock2)

Celsius

In [66]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      9     421
META      399.0      SEB   Y      8     194
TIKTAK    432.0      KOR   Y      7     212
OpenAI    482.0     CHIL   N      6     123
HNG       732.0      CHI   Y      5     283
Celsius   883.0      UAE   N      4      93
Alani     883.0      PHI   Y      3      93
Apple    1010.0      USA   Y      2     139
XKJ         NaN      JAP   N      1     333

In [67]:
sf.reset_index(inplace=True) # set index back to default integer index
print(sf)

     Stock   Price Location ETF  Valid  Shares
0   Google   320.0      CAN   Y      9     421
1     META   399.0      SEB   Y      8     194
2   TIKTAK   432.0      KOR   Y      7     212
3   OpenAI   482.0     CHIL   N      6     123
4      HNG   732.0      CHI   Y      5     283
5  Celsius   883.0      UAE   N      4      93
6    Alani   883.0      PHI   Y      3      93
7    Apple  1010.0      USA   Y      2     139
8      XKJ     NaN      JAP   N      1     333

In [68]:
max_ratio = sf.dropna(subset=['Price', 'Shares']).loc[:, ['Price', 'Shares']].apply(lambda x: x.Price/x.Shares, axis=1).max()
mask = (sf.Price/sf.Shares) == max_ratio
sf.loc[mask,:]
# retrieve the row(s) with the highest price to share ratio

     Stock  Price Location ETF  Valid  Shares
5  Celsius  883.0      UAE   N      4      93
6    Alani  883.0      PHI   Y      3      93

### Pandas Testing on Wine Reviews Dataset

In [69]:
import string
reviews = pd.read_csv('testing_dataset/winemag-data-130k-v2.csv', index_col=0)

In [70]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

#### Extract Counts of 'tropical'/'fruity' in Description Column

In [71]:
freq = {'tropical':0, 'fruity':0}
desc = [word.strip(string.punctuation).lower() for word in reviews.description[0].split()]
print(desc)
print(desc.count('tropical'))

['aromas', 'include', 'tropical', 'fruit', 'broom', 'brimstone', 'and', 'dried', 'herb', 'the', 'palate', "isn't", 'overly', 'expressive', 'offering', 'unripened', 'apple', 'citrus', 'and', 'dried', 'sage', 'alongside', 'brisk', 'acidity']
1

In [72]:
for word in desc:  
   if word in freq:
      freq[word] += 1

print(freq)

{'tropical': 1, 'fruity': 0}

In [73]:
tf = pd.DataFrame(data=freq, index=[0])

In [74]:
print(tf)

   tropical  fruity
0         1       0

In [75]:
reviews.description.head()

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
2    Tart and snappy, the flavors of lime flesh and...
3    Pineapple rind, lemon pith and orange blossom ...
4    Much like the regular bottling from 2012, this...
Name: description, dtype: object

In [76]:
def frequency(desc):
    filter_desc = [word.strip(string.punctuation).lower() for word in desc.description.split()]
    tropical_count = filter_desc.count('tropical')
    fruit_count = filter_desc.count('fruity')
    return tropical_count, fruit_count

x = reviews.apply(frequency, axis=1)
print(x)

0         (1, 0)
1         (0, 1)
2         (0, 0)
3         (0, 0)
4         (0, 0)
           ...
129966    (0, 0)
129967    (0, 0)
129968    (0, 1)
129969    (0, 0)
129970    (0, 0)
Length: 129971, dtype: object

In [77]:
y = x.map(lambda x: x[0]).sum(axis=0)

print(y)

3638

In [78]:
z = x.map(lambda x: x[1]).sum(axis=0)

print(z)

9466

In [79]:
pd.Series([y, z], index=['tropical', 'fruity'])

tropical    3638
fruity      9466
dtype: int64

In [80]:
tropical_count = reviews.description.map(lambda x: 'tropical' in x).sum() 
# count of reviews containing the word 'tropical', if true, counts as 1
fruity_count = reviews.description.map(lambda x: 'fruity' in x).sum()
# count of reviews containing the word 'fruity', if true, counts as 1

descriptor_count = pd.Series([tropical_count, fruity_count], index=['tropical', 'fruity'])
#return a series with index as the descriptor names and values as their respective counts

print(descriptor_count)

tropical    3607
fruity      9090
dtype: int64

### Star rating based on points and country

In [81]:
def wrapper(row):
    if ((row.points >= 95) & (row.country != 'Canada')) or (row.country == 'Canada'):
        return 3
    elif (row.points >= 85) & (row.country != 'Canada'):
        return 2
    else:
        return 1

star_ratings = reviews.apply(wrapper, axis=1)

print(star_ratings.value_counts())

2    114877
1     12421
3      2673
Name: count, dtype: int64

In [82]:
def wrapper(row):
    if ((row.points >= 95) & (row.country != 'Canada')) or (row.country == 'Canada'):
        row.points = 3
        return row
    elif (row.points >= 85) & (row.country != 'Canada'):
        row.points = 2
        return row
    else:
        row.points = 1
        return row

star_ratings = reviews.apply(wrapper, axis=1)

print(star_ratings.head().to_string())

# this returns a DataFrame with modified 'points' column based on the conditions

    country                                                                                                                                                                                                                                                description                         designation  points  price           province             region_1           region_2         taster_name taster_twitter_handle                                                                                title         variety               winery
0     Italy                                                                               Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity.                        Vulkà Bianco       2    NaN  Sicily & Sardinia                 Etna                NaN       Kerin O’Keefe          @kerinokeefe                                                    Nicosia 2013 Vulkà Bianco  (Etna)     White Blend              Nicosia
1  Portugal                        This is ripe and fruity, a wine that is smooth while still structured. Firm tannins are filled out with juicy red berry fruits and freshened with acidity. It's  already drinkable, although it will certainly be better from 2016.                            Avidagos       2   15.0              Douro                  NaN                NaN          Roger Voss            @vossroger                                        Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red  Quinta dos Avidagos
2        US                                                                 Tart and snappy, the flavors of lime flesh and rind dominate. Some green pineapple pokes through, with crisp acidity underscoring the flavors. The wine was all stainless-steel fermented.                                 NaN       2   14.0             Oregon    Willamette Valley  Willamette Valley        Paul Gregutt           @paulgwine                                         Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris            Rainstorm
3        US                                                    Pineapple rind, lemon pith and orange blossom start off the aromas. The palate is a bit more opulent, with notes of honey-drizzled guava and mango giving way to a slightly astringent, semidry finish.                Reserve Late Harvest       2   13.0           Michigan  Lake Michigan Shore                NaN  Alexander Peartree                   NaN                  St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)        Riesling           St. Julian
4        US  Much like the regular bottling from 2012, this comes across as rather rough and tannic, with rustic, earthy, herbal characteristics. Nonetheless, if you think of it as a pleasantly unfussy country wine, it's a good companion to a hearty winter stew.  Vintner's Reserve Wild Child Block       2   65.0             Oregon    Willamette Valley  Willamette Valley        Paul Gregutt           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)      Pinot Noir         Sweet Cheeks

## Grouping and Sorting

        However, often we want to group our data, and then do something specific to the group the data is in.

        As you'll learn, we do this with the groupby() operation. We'll also cover some additional topics, such as more complex ways to index your DataFrames, along with how to sort your data.

In [83]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [84]:
reviews.groupby('points').points.count() # count of reviews for each unique point value
# this is the same as review.points.value_counts().sort_index()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [85]:
reviews.groupby('points').price.sum()

points
80       6467.0
81      11684.0
82      33439.0
83      52633.0
84     117773.0
85     177591.0
86     259961.0
87     392628.0
88     459402.0
89     364289.0
90     530016.0
91     456621.0
92     452756.0
93     374571.0
94     280876.0
95     153585.0
96      76779.0
97      42885.0
98      16939.0
99       7958.0
100      9233.0
Name: price, dtype: float64

In [86]:
reviews.groupby('points').price.min() # cheapest wine in each point category

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

In [87]:
reviews.groupby('points').price.max() # most expensive wine in each point category

points
80       69.0
81      130.0
82      150.0
83      225.0
84      225.0
85      320.0
86      170.0
87      800.0
88     3300.0
89      500.0
90      510.0
91     2013.0
92      750.0
93      770.0
94     1125.0
95      973.0
96     2500.0
97     2000.0
98     1900.0
99      850.0
100    1500.0
Name: price, dtype: float64

In [88]:
for key, df in reviews.groupby('points'):
    print('Group:', key)
    print(df.head().to_string())
    break

Group: 80
       country                                                                                                                                                                                                                                                     description   designation  points  price       province        region_1 region_2        taster_name taster_twitter_handle                                                            title          variety                    winery
344      Chile                                         Aromas of pumpkin, squash and corn chips are stale and not inviting. There's an acceptable mouthfeel to this weird, unbalanced Chardonnay along with flavors of spiced squash, mealy apple and sautéed root vegetables.  Gran Reserva      80   19.0   Leyda Valley             NaN      NaN  Michael Schachner           @wineschach        Viña Tarapacá 2015 Gran Reserva Chardonnay (Leyda Valley)       Chardonnay             Viña Tarapacá
3640  Portugal                                                                                                                             Aromas of strawberry sherbet are followed by sweet candy-shop flavors on the palate. Chill it thoroughly before drinking. Screwcap.       Estreia      80    8.0    Vinho Verde             NaN      NaN         Roger Voss            @vossroger                        Viniverde 2011 Estreia Rosé (Vinho Verde)             Rosé                 Viniverde
3641     Chile                                                                 Fluffy, sweet aromas of peach, pear and vanilla are as good as it gets. Tastes of powdered sugar and the most forced oak you can imagine. Not at all surprising that it's resiny on the finish.       Reserve      80   15.0   Maule Valley             NaN      NaN  Michael Schachner           @wineschach            Cuevas del Sur 2010 Reserve Chardonnay (Maule Valley)       Chardonnay            Cuevas del Sur
4556     Italy                                                                                                        There's a thorny, almost raw quality of fruit here that is backed by a touch of dill weed and black tar. It feels tart and slightly bitter on the close.     Rondineto      80   12.0  Central Italy  Colli Aprutini      NaN                NaN                   NaN  Fattoria Giuseppe Savini 2011 Rondineto Merlot (Colli Aprutini)           Merlot  Fattoria Giuseppe Savini
4557     Spain  With dusty, candied aromas, the bouquet on this semisweet Cava is scattered all over the map. In the mouth, it's inoffensive, however the wine's candied, melony flavors are cloying and overtly sugary. This is too clumsy and candied to be taken seriously.      Demi Sec      80   14.0      Catalonia            Cava      NaN  Michael Schachner           @wineschach                        Paul Cheneau NV Demi Sec Sparkling (Cava)  Sparkling Blend              Paul Cheneau

In [89]:
# reviews.groupby('points').apply(lambda df: df.title.iloc[0]) soon depracated

# group by points and apply a function that returns the title of the first wine in each group

reviews.groupby('points').title.apply(lambda x: x.iloc[0])

points
80     Viña Tarapacá 2015 Gran Reserva Chardonnay (Le...
81     Pura 8 2010 Grand Reserve Pinot Noir (Rapel Va...
82       Mémoires 2015 Rosé (Coteaux Varois en Provence)
83         Koyle 2015 Costa Pinot Noir (Colchagua Costa)
84     Three Brothers 2014 Zero Degree Dry Riesling (...
85     Casa Silva 2008 Gran Reserva Petit Verdot (Col...
86     Clarksburg Wine Company 2010 Chenin Blanc (Cla...
87                     Nicosia 2013 Vulkà Bianco  (Etna)
88                  Fattoria Sardi 2015 Rosato (Toscana)
89           David Fulton 2008 Petite Sirah (St. Helena)
90     Beaumont 2005 Hope Marguerite Chenin Blanc (Wa...
91     Le Riche 2003 Cabernet Sauvignon Reserve Caber...
92     Dopff & Irion 2004 Schoenenbourg Grand Cru Ven...
93     Claiborne & Churchill 2014 Twin Creeks Estate ...
94         Sandeman 2015 Quinta do Seixo Vintage  (Port)
95     Jasper Hill 2013 Georgia's Paddock Shiraz (Hea...
96                        Oremus 2005 Eszencia  (Tokaji)
97     Robert Weil 2014 Kiedrich Gräfenberg Trockenbe...
98     Chambers Rosewood Vineyards NV Rare Muscadelle...
99     Quilceda Creek 2008 Cabernet Sauvignon (Columb...
100    Chambers Rosewood Vineyards NV Rare Muscat (Ru...
Name: title, dtype: object

In [90]:
# reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax(), :])
# This will be depracated
# return the wine with the highest points in each country and province group

idx = reviews.groupby(['country','province']).points.idxmax()
best = reviews.loc[idx,:]

In [91]:
idx

country    province
Argentina  Mendoza Province    82754
           Other               78303
Armenia    Armenia             66146
Australia  Australia Other     37882
           New South Wales     85337
                               ...
Uruguay    Juanico              9133
           Montevideo          15750
           Progreso            93103
           San Jose            39898
           Uruguay             39361
Name: points, Length: 425, dtype: int64

In [92]:
best.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
82754,Argentina,"If the color doesn't tell the full story, the ...",Nicasia Vineyard,97,120.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Bodega Catena Zapata 2006 Nicasia Vineyard Mal...,Malbec,Bodega Catena Zapata
78303,Argentina,"Take note, this could be the best wine Colomé ...",Reserva,95,90.0,Other,Salta,NaN,Michael Schachner,@wineschach,Colomé 2010 Reserva Malbec (Salta),Malbec,Colomé
66146,Armenia,"Deep salmon in color, this wine offers a bouqu...",Estate Bottled,88,15.0,Armenia,NaN,NaN,Mike DeSimone,@worldwineguys,Van Ardi 2015 Estate Bottled Rosé (Armenia),Rosé,Van Ardi
37882,Australia,Writes the book on how to make a wine filled w...,Sarah's Blend,93,15.0,Australia Other,South Eastern Australia,NaN,NaN,NaN,Marquis Philips 2000 Sarah's Blend Red (South ...,Red Blend,Marquis Philips
85337,Australia,De Bortoli's Noble One is as good as ever in 2...,Noble One Bortytis,94,32.0,New South Wales,New South Wales,NaN,Joe Czerwinski,@JoeCz,De Bortoli 2007 Noble One Bortytis Semillon (N...,Sémillon,De Bortoli

### agg() aggregate a bunch of function simultaneously

In [93]:
reviews.groupby(['country']).price.agg([len, min, max]).head() # return a dataframe with count, min, and max price for each country

/tmp/ipykernel_76389/1974734949.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  reviews.groupby(['country']).price.agg([len, min, max]).head() # return a dataframe with count, min, and max price for each country
/tmp/ipykernel_76389/1974734949.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  reviews.groupby(['country']).price.agg([len, min, max]).head() # return a dataframe with count, min, and max price for each country

                         len   min     max
country
Argentina               3800   4.0   230.0
Armenia                    2  14.0    15.0
Australia               2329   5.0   850.0
Austria                 3345   7.0  1100.0
Bosnia and Herzegovina     2  12.0    13.0

### Multi-indexes

        In all of the examples we've seen thus far we've been working with DataFrame or Series objects with a single-label index. groupby() is slightly different in the fact that, depending on the operation we run, it will sometimes result in what is called a multi-index.

        A multi-index differs from a regular index in that it has multiple levels. For example:

In [94]:
countries_reviewed = reviews.groupby(['country', 'province']).description.agg([len])
# return a dataframe with counts of reviews for each country and province combination

🔥 Summary (super simple)

        Grouping by ['country', 'province'] means:

        “Show me every unique combination of country + province found in the dataset.”

        For each combination, you get:

        one row in the output

        a multi-index (country, province)

        one aggregated value per column (here: description.agg(len))

So:

        Argentina + Mendoza Province → one group

        Argentina + Other → another group

        Australia + each province → more groups

In [95]:
countries_reviewed.head(10)

                              len
country   province
Argentina Mendoza Province   3264
          Other               536
Armenia   Armenia               2
Australia Australia Other     245
          New South Wales      85
          South Australia    1349
          Tasmania             42
          Victoria            322
          Western Australia   286
Austria   Austria              26

In [96]:
countries_location = reviews.groupby(['country', 'province'])

In [97]:
for key, df in countries_location:
    print("Group", key)
    print(df.head().to_string())
    break

Group ('Argentina', 'Mendoza Province')
       country                                                                                                                                                                                                                                                                                         description                designation  points  price          province       region_1 region_2        taster_name taster_twitter_handle                                                    title    variety              winery
17   Argentina                                               Raw black-cherry aromas are direct and simple but good. This has a juicy feel that thickens over time, with oak character and extract becoming more apparent. A flavor profile driven by dark-berry fruits and smoldering oak finishes meaty but hot.        Winemaker Selection      87   13.0  Mendoza Province        Mendoza      NaN  Michael Schachner           @wineschach  Gaucho Andino 2011 Winemaker Selection Malbec (Mendoza)     Malbec       Gaucho Andino
224  Argentina                                                                    Blackberry and road-tar aromas are dark and stout. This is moderately tannic and a bit rough and jagged on the palate. Flavors of stewed black plum and prune are ripe almost to an extreme, and that's how it finishes as well.                      Lunta      90   22.0  Mendoza Province  Luján de Cuyo      NaN  Michael Schachner           @wineschach                 Mendel 2014 Lunta Malbec (Luján de Cuyo)     Malbec              Mendel
231  Argentina                                         Meaty and rubbery, but that's young Bonarda. This is a sound wine with dark berry flavors, raisin and pulsing acidity. Still, there's modest roundness to the palate and length to the finish. Overall, it's tasty, full and borderline raisiny. Drink now.                        NaN      85   10.0  Mendoza Province        Mendoza      NaN  Michael Schachner           @wineschach                        Andean Sky 2007 Bonarda (Mendoza)    Bonarda          Andean Sky
253  Argentina  Huge in color and extract, but also a little childish. The nose has gumball, berry jam and a touch of volatility, but after things settle it rests on bold black fruit. It's not overly rich or sweet, and the feel is sort of sinewy. Seems more about size and color than refinement and polish.                    Reserve      85   15.0  Mendoza Province  Luján de Cuyo      NaN  Michael Schachner           @wineschach   Cueva de las Manos 2007 Reserve Malbec (Luján de Cuyo)     Malbec  Cueva de las Manos
261  Argentina                                  A blend of 50% Malbec with Cabernet, Syrah and Merlot that's lightly minty and full of tobacco, pepper and spicy aromas. Feels a bit clampy and tannic, with oaky, herbal flavors of plum and sweet berry. Shows a hint of green and drying tannins on the finish.  Estate Blend Gran Reserva      89   37.0  Mendoza Province            NaN      NaN  Michael Schachner           @wineschach               Algodon 2008 Estate Blend Gran Reserva Red  Red Blend             Algodon

In [98]:
countries_location.get_group(('Argentina', 'Mendoza Province')).head()
# return a dataframe with all reviews from Argentina, Mendoza Province group

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
17,Argentina,Raw black-cherry aromas are direct and simple ...,Winemaker Selection,87,13.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Gaucho Andino 2011 Winemaker Selection Malbec ...,Malbec,Gaucho Andino
224,Argentina,Blackberry and road-tar aromas are dark and st...,Lunta,90,22.0,Mendoza Province,Luján de Cuyo,NaN,Michael Schachner,@wineschach,Mendel 2014 Lunta Malbec (Luján de Cuyo),Malbec,Mendel
231,Argentina,"Meaty and rubbery, but that's young Bonarda. T...",NaN,85,10.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Andean Sky 2007 Bonarda (Mendoza),Bonarda,Andean Sky
253,Argentina,"Huge in color and extract, but also a little c...",Reserve,85,15.0,Mendoza Province,Luján de Cuyo,NaN,Michael Schachner,@wineschach,Cueva de las Manos 2007 Reserve Malbec (Luján ...,Malbec,Cueva de las Manos
261,Argentina,"A blend of 50% Malbec with Cabernet, Syrah and...",Estate Blend Gran Reserva,89,37.0,Mendoza Province,NaN,NaN,Michael Schachner,@wineschach,Algodon 2008 Estate Blend Gran Reserva Red,Red Blend,Algodon

In [99]:
countries_reviewed.index
# this is a multi-index with two levels: 'country' and 'province'
# because we grouped by two columns, the resulting DataFrame has a multi-index with two levels

MultiIndex([('Argentina',  'Mendoza Province'),
            ('Argentina',             'Other'),
            (  'Armenia',           'Armenia'),
            ('Australia',   'Australia Other'),
            ('Australia',   'New South Wales'),
            ('Australia',   'South Australia'),
            ('Australia',          'Tasmania'),
            ('Australia',          'Victoria'),
            ('Australia', 'Western Australia'),
            (  'Austria',           'Austria'),
            ...
            (       'US',        'Washington'),
            (       'US', 'Washington-Oregon'),
            (  'Ukraine',           'Ukraine'),
            (  'Uruguay',         'Atlantida'),
            (  'Uruguay',         'Canelones'),
            (  'Uruguay',           'Juanico'),
            (  'Uruguay',        'Montevideo'),
            (  'Uruguay',          'Progreso'),
            (  'Uruguay',          'San Jose'),
            (  'Uruguay',           'Uruguay')],
           names=['country', 'province'], length=425)

In [100]:
countries_reviewed.head()

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
Armenia   Armenia              2
Australia Australia Other    245
          New South Wales     85

In [101]:
countries_reviewed.reset_index(inplace=True)

### SORTING

In [102]:
countries_reviewed.sort_values(by='len')

          country                  province    len
40         Brazil          Serra do Sudeste      1
63          Chile                   Coelemu      1
354  South Africa                Paardeberg      1
48         Canada              Canada Other      1
58          Chile  Casablanca-Curicó Valley      1
..            ...                       ...    ...
409            US                    Oregon   5373
227         Italy                   Tuscany   5897
118        France                  Bordeaux   5941
415            US                Washington   8639
392            US                California  36247

[425 rows x 3 columns]

In [103]:
countries_reviewed.sort_values(by='len', ascending=False).head(10)

       country          province    len
392         US        California  36247
415         US        Washington   8639
118     France          Bordeaux   5941
227      Italy           Tuscany   5897
409         US            Oregon   5373
119     France          Burgundy   3980
375      Spain    Northern Spain   3851
224      Italy          Piedmont   3729
0    Argentina  Mendoza Province   3264
228      Italy            Veneto   2716

In [104]:
countries_reviewed.sort_index().head(10)

     country           province   len
0  Argentina   Mendoza Province  3264
1  Argentina              Other   536
2    Armenia            Armenia     2
3  Australia    Australia Other   245
4  Australia    New South Wales    85
5  Australia    South Australia  1349
6  Australia           Tasmania    42
7  Australia           Victoria   322
8  Australia  Western Australia   286
9    Austria            Austria    26

In [105]:
countries_reviewed.sort_values(by=['country', 'len']).head(10)

      country           province   len
1   Argentina              Other   536
0   Argentina   Mendoza Province  3264
2     Armenia            Armenia     2
6   Australia           Tasmania    42
4   Australia    New South Wales    85
3   Australia    Australia Other   245
8   Australia  Western Australia   286
7   Australia           Victoria   322
5   Australia    South Australia  1349
20    Austria      Südburgenland     2

In [106]:
print(reviews.head().to_string())

    country                                                                                                                                                                                                                                                description                         designation  points  price           province             region_1           region_2         taster_name taster_twitter_handle                                                                                title         variety               winery
0     Italy                                                                               Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity.                        Vulkà Bianco      87    NaN  Sicily & Sardinia                 Etna                NaN       Kerin O’Keefe          @kerinokeefe                                                    Nicosia 2013 Vulkà Bianco  (Etna)     White Blend              Nicosia
1  Portugal                        This is ripe and fruity, a wine that is smooth while still structured. Firm tannins are filled out with juicy red berry fruits and freshened with acidity. It's  already drinkable, although it will certainly be better from 2016.                            Avidagos      87   15.0              Douro                  NaN                NaN          Roger Voss            @vossroger                                        Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red  Quinta dos Avidagos
2        US                                                                 Tart and snappy, the flavors of lime flesh and rind dominate. Some green pineapple pokes through, with crisp acidity underscoring the flavors. The wine was all stainless-steel fermented.                                 NaN      87   14.0             Oregon    Willamette Valley  Willamette Valley        Paul Gregutt           @paulgwine                                         Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris            Rainstorm
3        US                                                    Pineapple rind, lemon pith and orange blossom start off the aromas. The palate is a bit more opulent, with notes of honey-drizzled guava and mango giving way to a slightly astringent, semidry finish.                Reserve Late Harvest      87   13.0           Michigan  Lake Michigan Shore                NaN  Alexander Peartree                   NaN                  St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)        Riesling           St. Julian
4        US  Much like the regular bottling from 2012, this comes across as rather rough and tannic, with rustic, earthy, herbal characteristics. Nonetheless, if you think of it as a pleasantly unfussy country wine, it's a good companion to a hearty winter stew.  Vintner's Reserve Wild Child Block      87   65.0             Oregon    Willamette Valley  Willamette Valley        Paul Gregutt           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)      Pinot Noir         Sweet Cheeks

### 1.

        Who are the most common wine reviewers in the dataset? Create a Series whose index is the taster_twitter_handle category from the dataset, and whose values count how many reviews each person wrote.

In [107]:
test = reviews.groupby('taster_twitter_handle')

In [108]:
test.get_group(('@vossroger')).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer
30,France,Red cherry fruit comes laced with light tannin...,Nouveau,86,NaN,Beaujolais,Beaujolais-Villages,NaN,Roger Voss,@vossroger,Domaine de la Madone 2012 Nouveau (Beaujolais...,Gamay,Domaine de la Madone

In [109]:
test.taster_twitter_handle.count() # return a series with counts of reviews for each taster_twitter_handle

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
Name: taster_twitter_handle, dtype: int64

In [110]:
reviews.groupby('taster_twitter_handle').taster_twitter_handle.count()
# first, group by taster_twitter_handle, then count non-null entries in the taster_twitter_handle column for each group

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
Name: taster_twitter_handle, dtype: int64

In [111]:
for key, df in reviews.groupby('taster_twitter_handle'):
    print(f'Key: {key}')
    print(df.head().to_string())
    break

Key: @AnneInVino
     country                                                                                                                                                                                                                                                                                                                                description      designation  points  price       province region_1 region_2       taster_name taster_twitter_handle                                                     title           variety                 winery
93   Austria                                                                                                                                                   Freshness characterizes the nose: green pear, ivy leaves and citrus notes play on nose and palate. This is light footed, easy drinking and charming. Drink soon while flavors are fresh.              NaN      88   12.0     Burgenland      NaN      NaN  Anne Krebiehl MW           @AnneInVino                  Fuchs 2015 Grüner Veltliner (Burgenland)  Grüner Veltliner                  Fuchs
340   France                                                                                                                                                                                        The nose is muted, despite the slight spritz of the wine, while the palate is equally toned down. It's a rounded if not very expressive white wine.        Tradition      82   18.0         Alsace   Alsace      NaN  Anne Krebiehl MW           @AnneInVino  Antoine Moltès & Fils 2015 Tradition Pinot Gris (Alsace)        Pinot Gris  Antoine Moltès & Fils
423  Austria                                                                                                              There is a savory, fragrant, mossy greenness that draws you in. On the concentrated palate, this becomes more distinct as the peel of Bosc pear and crushed arugula emerge. Lime zestiness comes with a slightly warm finish.            Kittl      89   23.0    Weinviertel      NaN      NaN  Anne Krebiehl MW           @AnneInVino            Kohl 2015 Kittl Grüner Veltliner (Weinviertel)  Grüner Veltliner                   Kohl
428  Austria                                                                                                 An earthy hint colors the pear notes which on the palate acquire a fresh, almost floral quality. The earthy tone of yeast and miso provides a counterpoint to the zesty, lime-peel freshness. The finish is clean-cut and very refreshing.  Crazy Creatures      89   17.0       Kremstal      NaN      NaN  Anne Krebiehl MW           @AnneInVino    Malat 2015 Crazy Creatures Grüner Veltliner (Kremstal)  Grüner Veltliner                  Malat
435  Austria  Creamy notes pear crumble make for a most attractive nose. The palate follows with gentle softness and concentration, supported by bright, fresh acidity. The creamy notes continue alongside notes of green and red apple and fresh pear. There is a lot of substance and body, so have this alongside a meal, the finish is superclean.      Lage Modler      89    NaN  Thermenregion      NaN      NaN  Anne Krebiehl MW           @AnneInVino   Gebeshuber 2015 Lage Modler Zierfandler (Thermenregion)       Zierfandler             Gebeshuber

### 2.
        What is the best wine I can buy for a given amount of money? Create a Series whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending (so that 4.0 dollars is at the top and 3300.0 dollars is at the bottom).

In [112]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [113]:
test = reviews.groupby('price')

In [114]:
test.get_group(15.0).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
36,Chile,"White flower, lychee and apple aromas carry th...",Estate,86,15.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Estampa 2011 Estate Viognier-Chardonnay (Colch...,Viognier-Chardonnay,Estampa
53,France,"Fruity and lightly herbaceous, this has fine t...",La Fleur d'Amélie,85,15.0,Bordeaux,Bordeaux Blanc,NaN,Roger Voss,@vossroger,Château de Sours 2011 La Fleur d'Amélie (Bord...,Bordeaux-style White Blend,Château de Sours
66,France,"This soft, rounded wine is ripe with generous ...",NaN,86,15.0,Burgundy,Mâcon-Milly Lamartine,NaN,Roger Voss,@vossroger,Vignerons des Terres Secrètes 2015 Mâcon-Mill...,Chardonnay,Vignerons des Terres Secrètes

In [115]:
reviews.groupby('price').points.max().sort_index()

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

### 3.
        What are the minimum and maximum prices for each variety of wine? Create a DataFrame whose index is the variety category from the dataset and whose values are the min and max values thereof.

In [116]:
reviews.groupby('variety').agg({'points': 'sum', 'price': 'max',})
# return a DataFrame with total points and max price for each variety

             points  price
variety
Abouriou        263   75.0
Agiorgitiko    5483   66.0
Aglianico     32050  180.0
Aidani           82   27.0
Airen           245   10.0
...             ...    ...
Zinfandel    238367  100.0
Zlahtina        172   16.0
Zweigelt      18454   70.0
Çalkarası       173   19.0
Žilavka          88   15.0

[707 rows x 2 columns]

In [117]:
reviews.groupby('variety').agg(
    points_sum = ('points', 'sum'),
    price_min = ('price', 'min'),
    price_max= ('price', 'max') 
)
# returns a DataFrame with a MultiIndex column 
# for price (min,max)

             points_sum  price_min  price_max
variety
Abouriou            263       15.0       75.0
Agiorgitiko        5483       10.0       66.0
Aglianico         32050        6.0      180.0
Aidani               82       27.0       27.0
Airen               245        8.0       10.0
...                 ...        ...        ...
Zinfandel        238367        5.0      100.0
Zlahtina            172       13.0       16.0
Zweigelt          18454        9.0       70.0
Çalkarası           173       19.0       19.0
Žilavka              88       15.0       15.0

[707 rows x 3 columns]

In [118]:
reviews.groupby('variety').price.agg(['min', 'max'])
# returns a DataFrame with a MultiIndex column for price (min,max)

              min    max
variety
Abouriou     15.0   75.0
Agiorgitiko  10.0   66.0
Aglianico     6.0  180.0
Aidani       27.0   27.0
Airen         8.0   10.0
...           ...    ...
Zinfandel     5.0  100.0
Zlahtina     13.0   16.0
Zweigelt      9.0   70.0
Çalkarası    19.0   19.0
Žilavka      15.0   15.0

[707 rows x 2 columns]

### 4.
        What are the most expensive wine varieties? Create a variable `sorted_varieties` containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).

In [119]:
reviews.groupby('variety').price.agg(['min', 'max']).sort_values(by=['min', 'max'], ascending=False).head(30)

                              min    max
variety
Ramisco                     495.0  495.0
Terrantez                   236.0  236.0
Francisa                    160.0  160.0
Rosenmuskateller            150.0  150.0
Tinta Negra Mole            112.0  112.0
Pignolo                      70.0   70.0
Syrah-Cabernet Franc         60.0   69.0
Garnacha-Cariñena            57.0   57.0
Doña Blanca                  53.0   53.0
Cercial                      50.0   50.0
Mavrotragano                 50.0   50.0
Sercial                      50.0   50.0
Pugnitello                   49.0   49.0
Malbec-Cabernet              45.0  165.0
Tinta del Pais               45.0   50.0
Touriga                      45.0   46.0
Babosa Negro                 45.0   45.0
Cabernet Sauvignon-Barbera   45.0   45.0
Syrah-Grenache-Viognier      45.0   45.0
Tinta Madeira                45.0   45.0
Vermentino Nero              45.0   45.0
Malbec-Carménère             43.0   43.0
Madeira Blend                42.0   49.0
Albarossa                    40.0   40.0
Colorino                     40.0   40.0
Favorita                     40.0   40.0
Früburgunder                 40.0   40.0
Moscato di Noto              40.0   40.0
Riesling-Chardonnay          40.0   40.0
Ryzlink Rýnský               40.0   40.0

## 5.
Create a `Series` whose index is reviewers and whose values is the average review score given out by that reviewer. Hint: you will need the `taster_name` and `points` columns.

In [120]:
test = reviews.groupby('taster_name').points
# return a series with taster_name as index and points as values

In [121]:
test.get_group('Roger Voss')
# retrieve all points reviews by taster 'Roger Voss'

1         87
7         87
9         87
11        87
30        86
          ..
129964    90
129965    90
129968    90
129969    90
129970    90
Name: points, Length: 25514, dtype: int64

In [122]:
test.groups.keys()
# return the list of taster names (group keys)

dict_keys(['Alexander Peartree', 'Anna Lee C. Iijima', 'Anne Krebiehl\xa0MW', 'Carrie Dykes', 'Christina Pickard', 'Fiona Adams', 'Jeff Jenssen', 'Jim Gordon', 'Joe Czerwinski', 'Kerin O’Keefe', 'Lauren Buzzeo', 'Matt Kettmann', 'Michael Schachner', 'Mike DeSimone', 'Paul Gregutt', 'Roger Voss', 'Sean P. Sullivan', 'Susan Kostrzewa', 'Virginie Boone'])

In [123]:
reviews.groupby('taster_name').points.mean()
# return the mean points for each taster_name group

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
Anne Krebiehl MW      90.562551
Carrie Dykes          86.395683
Christina Pickard     87.833333
Fiona Adams           86.888889
Jeff Jenssen          88.319756
Jim Gordon            88.626287
Joe Czerwinski        88.536235
Kerin O’Keefe         88.867947
Lauren Buzzeo         87.739510
Matt Kettmann         90.008686
Michael Schachner     86.907493
Mike DeSimone         89.101167
Paul Gregutt          89.082564
Roger Voss            88.708003
Sean P. Sullivan      88.755739
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, dtype: float64

In [124]:
reviews.groupby('taster_name').points.mean().describe()
# describe the statistical summary of the mean points for each taster_name group

count    19.000000
mean     88.233026
std       1.243610
min      85.855422
25%      87.323501
50%      88.536235
75%      88.975256
max      90.562551
Name: points, dtype: float64

### 6.
        What combination of countries and varieties are most common? Create a `Series` whose index is a `MultiIndex`of `{country, variety}` pairs. For example, a pinot noir produced in the US should map to `{"US", "Pinot Noir"}`. Sort the values in the `Series` in descending order based on wine count.

In [125]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [126]:
test = reviews.groupby(['country', 'variety'])

In [127]:
test.get_group(('US', 'Pinot Noir')).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
21,US,"A sleek mix of tart berry, stem and herb, alon...",NaN,87,20.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Acrobat 2013 Pinot Noir (Oregon),Pinot Noir,Acrobat
25,US,Oak and earth intermingle around robust aromas...,King Ridge Vineyard,87,69.0,California,Sonoma Coast,Sonoma,Virginie Boone,@vboone,Castello di Amorosa 2011 King Ridge Vineyard P...,Pinot Noir,Castello di Amorosa
35,US,As with many of the Erath 2010 vineyard design...,Hyland,86,50.0,Oregon,McMinnville,Willamette Valley,Paul Gregutt,@paulgwine,Erath 2010 Hyland Pinot Noir (McMinnville),Pinot Noir,Erath
41,US,"A stiff, tannic wine, this slowly opens and br...",NaN,86,22.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Hawkins Cellars 2009 Pinot Noir (Willamette Va...,Pinot Noir,Hawkins Cellars

In [128]:
reviews.groupby(['country', 'variety']).size().sort_values(ascending=False)
# return a series with MultiIndex (country, variety) and counts of reviews for each combination

country  variety
US       Pinot Noir                    9885
         Cabernet Sauvignon            7315
         Chardonnay                    6801
France   Bordeaux-style Red Blend      4725
Italy    Red Blend                     3624
                                       ...
Spain    Premsal                          1
China    Cabernet Blend                   1
Spain    Mataro                           1
         Merseguera-Sauvignon Blanc       1
France   Gros Plant                       1
Length: 1612, dtype: int64

In [129]:
print(sf)

     Stock   Price Location ETF  Valid  Shares
0   Google   320.0      CAN   Y      9     421
1     META   399.0      SEB   Y      8     194
2   TIKTAK   432.0      KOR   Y      7     212
3   OpenAI   482.0     CHIL   N      6     123
4      HNG   732.0      CHI   Y      5     283
5  Celsius   883.0      UAE   N      4      93
6    Alani   883.0      PHI   Y      3      93
7    Apple  1010.0      USA   Y      2     139
8      XKJ     NaN      JAP   N      1     333

In [130]:
sf.shape # return 9 rows, 7 columns

(9, 6)

In [131]:
sf.shape[0] # return number of rows

9

In [132]:
sf.shape[1] # return number of columns

6

In [133]:
sf.size # return total number of elements (rows * columns) = 54

54

### Data Types and Missing Values

        The data type for a column in a DataFrame or a Series is known as the dtype.

        You can use the dtype property to grab the type of a specific column. For instance, we can get the dtype of the price column in the reviews DataFrame:

In [134]:
reviews.price.dtype

dtype('float64')

In [135]:
reviews.dtypes

country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

        Data types tell us something about how pandas is storing the data internally. float64 means that it's using a 64-bit floating point number; int64 means a similarly sized integer instead, and so on.

        One peculiarity to keep in mind (and on display very clearly here) is that columns consisting entirely of strings do not get their own type; they are instead given the object type.

        It's possible to convert a column of one type into another wherever such a conversion makes sense by using the astype() function. For example, we may transform the points column from its existing int64 data type into a float64 data type:

In [136]:
reviews.points.astype('float64')

0         87.0
1         87.0
2         87.0
3         87.0
4         87.0
          ...
129966    90.0
129967    90.0
129968    90.0
129969    90.0
129970    90.0
Name: points, Length: 129971, dtype: float64

In [137]:
reviews.index.dtype

dtype('int64')

        Missing data
        Entries missing values are given the value NaN, short for "Not a Number". For technical reasons these NaN values are always of the float64 dtype.

        Pandas provides some methods specific to missing data. To select NaN entries you can use pd.isnull() (or its companion pd.notnull()). This is meant to be used thusly:

In [138]:
reviews[pd.isnull(reviews.country)].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
913,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines
3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier
4243,NaN,"Violet-red in color, this semisweet wine has a...",Red Naturally Semi-Sweet,88,18.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Kakhetia Traditional Winemaking 2012 Red Natur...,Ojaleshi,Kakhetia Traditional Winemaking
9509,NaN,This mouthwatering blend starts with a nose of...,Theopetra Malagouzia-Assyrtiko,92,28.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...,White Blend,Tsililis
9750,NaN,This orange-style wine has a cloudy yellow-gol...,Orange Nikolaevo Vineyard,89,28.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Ross-idi 2015 Orange Nikolaevo Vineyard Chardo...,Chardonnay,Ross-idi

In [139]:
reviews.region_2.isnull()

0          True
1          True
2         False
3          True
4         False
          ...
129966     True
129967    False
129968     True
129969     True
129970     True
Name: region_2, Length: 129971, dtype: bool

In [140]:
reviews.region_2

0                       NaN
1                       NaN
2         Willamette Valley
3                       NaN
4         Willamette Valley
                ...
129966                  NaN
129967         Oregon Other
129968                  NaN
129969                  NaN
129970                  NaN
Name: region_2, Length: 129971, dtype: object

        Replacing missing values is a common operation. Pandas provides a really handy method for this problem: fillna(). fillna() provides a few different strategies for mitigating such data. For example, we can simply replace each NaN with an "Unknown":

In [141]:
reviews.region_2.fillna("Unknown")

0                   Unknown
1                   Unknown
2         Willamette Valley
3                   Unknown
4         Willamette Valley
                ...
129966              Unknown
129967         Oregon Other
129968              Unknown
129969              Unknown
129970              Unknown
Name: region_2, Length: 129971, dtype: object

In [142]:
reviews.taster_twitter_handle.replace('@kerinokeefe', '@kerino')

0             @kerino
1          @vossroger
2         @paulgwine
3                 NaN
4         @paulgwine
             ...
129966            NaN
129967    @paulgwine
129968     @vossroger
129969     @vossroger
129970     @vossroger
Name: taster_twitter_handle, Length: 129971, dtype: object

## 3.
        Sometimes the price column is null. How many reviews in the dataset are missing a price?

In [143]:
reviews.loc[pd.isna(reviews.price)].shape[0]

8996

In [144]:
# another way to find this is:
reviews.price.isna().sum()
# sum all True values in the boolean series, where True indicates a null price

np.int64(8996)

## 4.
What are the most common wine-producing regions? Create a Series counting the number of times each value occurs in the `region_1` field. This field is often missing data, so replace missing values with `Unknown`. Sort in descending order.  Your output should look something like this:

```
Unknown                    21247
Napa Valley                 4480
                           ...  
Bardolino Superiore            1
Primitivo del Tarantino        1
Name: region_1, Length: 1230, dtype: int64
```

In [145]:
reviews.region_1.fillna('Unknown').value_counts()

region_1
Unknown                               21247
Napa Valley                            4480
Columbia Valley (WA)                   4124
Russian River Valley                   3091
California                             2629
                                      ...
Sonoma-Napa-Lake                          1
Sonoma County-Santa Barbara County        1
Del Veneto                                1
Bardolino Superiore                       1
Paestum                                   1
Name: count, Length: 1230, dtype: int64

In [146]:
reviews.region_1.fillna('Unknown', axis=0, inplace=True)

/tmp/ipykernel_76389/566892298.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  reviews.region_1.fillna('Unknown', axis=0, inplace=True)

In [147]:
reviews.region_1.value_counts()

region_1
Unknown                               21247
Napa Valley                            4480
Columbia Valley (WA)                   4124
Russian River Valley                   3091
California                             2629
                                      ...
Sonoma-Napa-Lake                          1
Sonoma County-Santa Barbara County        1
Del Veneto                                1
Bardolino Superiore                       1
Paestum                                   1
Name: count, Length: 1230, dtype: int64

### Renaming and Combining

        Oftentimes data will come to us with column names, index names, or other naming conventions that we are not satisfied with. In that case, you'll learn how to use pandas functions to change the names of the offending entries to something better.

        You'll also explore how to combine data from multiple DataFrames and/or Series.

#### Renaming

In [148]:
reviews.rename(columns={'points': 'score'}).head()

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,Unknown,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [149]:
reviews.rename(index={0: 'firstEntry', 1: 'secondEntry', 3: 'threeisthree'}).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
firstEntry,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
secondEntry,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,Unknown,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
threeisthree,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

        You'll probably rename columns very often, but rename index values very rarely. For that, set_index() is usually more convenient.

        Both the row index and the column index can have their own name attribute. The complimentary rename_axis() method may be used to change these names. For example:

In [150]:
reviews.rename_axis("wines", axis='rows', inplace=True)
reviews.rename_axis("fields", axis='columns', inplace=True)

In [151]:
reviews.head()

fields,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
wines,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,Unknown,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [152]:
reviews.rename_axis('items', axis='rows').rename_axis('types', axis='columns').head()
# temporary rename of axis without modifying the original DataFrame

types,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
items,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,Unknown,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

### Combining

In [153]:
canadian_youtube = pd.read_csv('testing_dataset/CAvideos.csv')

In [154]:
british_youtube = pd.read_csv('testing_dataset/GBvideos.csv')

In [155]:
canadian_youtube.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...

In [156]:
british_youtube.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...

        The simplest combining method is concat(). Given a list of elements, this function will smush those elements together along an axis.

        This is useful when we have data in different DataFrame or Series objects but having the same fields (columns). One example: the YouTube Videos dataset, which splits the data up based on country of origin (e.g. Canada and the UK, in this example). If we want to study multiple countries simultaneously, we can use concat() to smush them together:

In [157]:
print(pd.concat([canadian_youtube, british_youtube]).head().to_string())

      video_id trending_date                                                  title channel_title  category_id              publish_time                                                                                                                                                                                                                                                                                                                        tags     views    likes  dislikes  comment_count                                  thumbnail_link  comments_disabled  ratings_disabled  video_error_or_removed                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         description
0  n1WpP7iowLc      17.14.11             Eminem - Walk On Water (Audio) ft. Beyoncé    EminemVEVO           10  2017-11-10T17:00:03.000Z                                                                                                                                                                                                                                                               Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/Interscope"|"Rap"  17158579   787425     43420         125882  https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg              False             False                   False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Eminem's new track Walk on Water ft. Beyoncé is available everywhere: http://shady.sr/WOWEminem \nPlaylist Best of Eminem: https://goo.gl/AquNpo\nSubscribe for more: https://goo.gl/DxCrDV\n\nFor more visit: \nhttp://eminem.com\nhttp://facebook.com/eminem\nhttp://twitter.com/eminem\nhttp://instagram.com/eminem\nhttp://eminem.tumblr.com\nhttp://shadyrecords.com\nhttp://facebook.com/shadyrecords\nhttp://twitter.com/shadyrecords\nhttp://instagram.com/shadyrecords\nhttp://trustshady.tumblr.com\n\nMusic video by Eminem performing Walk On Water. (C) 2017 Aftermath Records\nhttp://vevo.ly/gA7xKt
1  0dBIkQ4Mz1M      17.14.11                          PLUSH - Bad Unboxing Fan Mail     iDubbbzTV           23  2017-11-13T17:00:00.000Z                                                                                                                                                                                                   plush|"bad unboxing"|"unboxing"|"fan mail"|"idubbbztv"|"idubbbztv2"|"things"|"best"|"packages"|"plushies"|"chontent chop"   1014651   127794      1688          13030  https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg              False             False                   False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    STill got a lot of packages. Probably will last for another year. On a side note, more 2nd channel vids soon. editing with premiere from now on, gon' be a tedious transition, but i think it's for the best. \n\n__\n\nSUBSCRIBE ► http://www.youtube.com/subscription_center?add_user=iDubbbztv\n\nMain Channel ► https://www.youtube.com/user/iDubbbzTV\nSecond Channel ► https://www.youtube.com/channel/UC-tsNNJ3yIW98MtPH6PWFAQ\nGaming Channel ► https://www.youtube.com/channel/UCVhfFXNY0z3-mbrTh1OYRXA\n\nWebsite ► http://www.idubbbz.com/\n\nInstagram ► https://instagram.com/idubbbz/\nTwitter ► https://twitter.com/Idubbbz\nFacebook ► http://www.facebook.com/IDubbbz\nTwitch ► http://www.twitch.tv/idubbbz\n_
2  5qpjK5DgCt4      17.14.11  Racist Superman | Rudy Mancuso, King Bach & Lele Pons  Rudy Mancuso           23  2017-11-12T19:05:24.000Z  racist superman|"rudy"|"mancuso"|"king"|"bach"|"racist"|"superman"|"love"|"rudy mancuso poo bear black white official music video"|"iphone x by pineapple"|"lelepons"|"hannahstocking"|"rudymancuso"|"inanna"|"anwar"|"sarkis"|"shots"|"shotsstudios"|"alesso"|"anitta"|"brazil"|"Getting My Driver's License | Lele Pons"   3191434   146035      5339           8181  https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg              False             False                   False                                                                           WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► https://www.youtube.com/channel/UC5jkXpfnBhlDjqh0ir5FsIQ?sub_confirmation=1\n\nTHANKS FOR WATCHING! LIKE & SUBSCRIBE FOR MORE VIDEOS!\n-----------------------------------------------------------\nFIND ME ON: \nInstagram | http://instagram.com/rudymancuso\nTwitter | http://twitter.com/rudymancuso\nFacebook | http://facebook.com/rudymancuso\n\nCAST: \nRudy Mancuso | http://youtube.com/c/rudymancuso\nLele Pons | http://youtube.com/c/lelepons\nKing Bach | https://youtube.com/user/BachelorsPadTv\n\nVideo Effects: \nCaleb Natale | https://instagram.com/calebnatale\n\nPA:\nPaulina Gregory\n\n\nShots Studios Channels:\nAlesso | https://youtube.com/c/alesso\nAnitta | http://youtube.com/c/anitta\nAnwar Jibawi | http://youtube.com/c/anwar\nAwkward Puppets | http://youtube.com/c/awkwardpuppets\nHannah Stocking | http://youtube.com/c/hannahstocking\nInanna Sarkis | http://youtube.com/c/inanna\nLele Pons | http://youtube.com/c/lelepons\nMaejor | http://youtube.com/c/maejor\nMike Tyson | http://youtube.com/c/miketyson \nRudy Mancuso | http://youtube.com/c/rudymancuso\nShots Studios | http://youtube.com/c/shots\n\n#Rudy\n#RudyMancuso
3  d380meD0W0M      17.14.11                               I Dare You: GOING BALD!?      nigahiga           24  2017-11-12T18:01:41.000Z                                                                                                                                                                                                    ryan|"higa"|"higatv"|"nigahiga"|"i dare you"|"idy"|"rhpc"|"dares"|"no truth"|"comments"|"comedy"|"funny"|"stupid"|"fail"   2095828   132239      1989          17518  https://i.ytimg.com/vi/d380meD0W0M/default.jpg              False             False                   False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        I know it's been a while since we did this show, but we're back with what might be the best episode yet!\nLeave your dares in the comment section! \n\nOrder my book how to write good \nhttp://higatv.com/ryan-higas-how-to-write-good-pre-order-links/\n\nJust Launched New Official Store\nhttps://www.gianthugs.com/collections/ryan\n\nHigaTV Channel\nhttp://www.youtube.com/higatv\n\nTwitter\nhttp://www.twitter.com/therealryanhiga\n\nFacebook\nhttp://www.facebook.com/higatv\n\nWebsite\nhttp://www.higatv.com\n\nInstagram\nhttp://www.instagram.com/notryanhiga\n\nSend us mail or whatever you want here!\nPO Box 232355\nLas Vegas, NV 89105
4  2Vv-BfVoq4g      17.14.11            Ed Sheeran - Perfect (Official Music Video)    Ed Sheeran           10  2017-11-09T11:04:14.000Z                                                                                                                                                                                                                     edsheeran|"ed sheeran"|"acoustic"|"live"|"cover"|"official"|"remix"|"official video"|"lyrics"|"session"  33523622  1634130     21082          85067  https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg              False             False                   False  🎧: https://ad.gt/yt-perfect\n💰: https://atlanti.cr/yt-album\nSubscribe to Ed's channel: http://bit.ly/SubscribeToEdSheeran\n\nFollow Ed on...\nFacebook: http://www.facebook.com/EdSheeranMusic\nTwitter: http://twitter.com/edsheeran\nInstagram: http://instagram.com/teddysphotos\nOfficial Website: http://edsheeran.com\n\nDirector: Jason Koenig\nProducer: Honna Kimmerer\nStarring: Ed Sheeran & Zoey Deutch \nDirector of Photography: Johnny Valencia\nProduction Company: Anonymous Content\nExec Producer: Nina Soriano\nProduction Manager: Doug Hoff\nCommissioner: Dan Curwin\nProduction Designer: John Lavin\nLead Casting: Amy Hubbard \n \nWritten by: Jason Koenig, Ed Sheeran, Andrew Kolvet, Jenny Koenig, Murray Cummings\n\nEdited by: Jason Koenig & Johnny Valencia\nVFX: Ian Hubert\n\nCast: Bo Valencia, Dennis Ranalta, Arthur Pauli\n \nSki Cinematography: Corey Koniniec\nSpecialty Camera op: Ryan Haug\n1st AC: Ryan Brown\n \n1st Assistant Director: Ole Zapatka\nArt Director: Klaus Hartl\nSnow fx: Lucien Stephenson\n\nGaffer: Thomas Berz\nStylist: Claudia Lajda\nHair & Makeup: Christel Thoresen\nAustrian Casting: Ursula Kiplinger\n \nAdditional VFX: Zoic\n\nSpecial Thanks to: The Hintertux Glacier, Austria;\nThe Tenne, and Hotel Neuhintertux

        The middlemost combiner in terms of complexity is join(). join() lets you combine different DataFrame objects which have an index in common. For example, to pull down videos that happened to be trending on the same day in both Canada and the UK, we could do the following:

In [158]:
left = canadian_youtube.set_index(['title', 'trending_date'])
right = british_youtube.set_index(['title', 'trending_date'])

print(left.join(right, lsuffix='_CAN', rsuffix='_UK').head().to_string())

                                                                    video_id_CAN channel_title_CAN  category_id_CAN          publish_time_CAN                                                                                                                                                                                                                                                                                                                    tags_CAN  views_CAN  likes_CAN  dislikes_CAN  comment_count_CAN                              thumbnail_link_CAN  comments_disabled_CAN  ratings_disabled_CAN  video_error_or_removed_CAN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     description_CAN  video_id_UK channel_title_UK  category_id_UK           publish_time_UK                                                                                                  tags_UK    views_UK   likes_UK  dislikes_UK  comment_count_UK                               thumbnail_link_UK comments_disabled_UK ratings_disabled_UK video_error_or_removed_UK                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      description_UK
title                                                 trending_date
Eminem - Walk On Water (Audio) ft. Beyoncé            17.14.11       n1WpP7iowLc        EminemVEVO               10  2017-11-10T17:00:03.000Z                                                                                                                                                                                                                                                               Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/Interscope"|"Rap"   17158579     787425         43420             125882  https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg                  False                 False                       False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Eminem's new track Walk on Water ft. Beyoncé is available everywhere: http://shady.sr/WOWEminem \nPlaylist Best of Eminem: https://goo.gl/AquNpo\nSubscribe for more: https://goo.gl/DxCrDV\n\nFor more visit: \nhttp://eminem.com\nhttp://facebook.com/eminem\nhttp://twitter.com/eminem\nhttp://instagram.com/eminem\nhttp://eminem.tumblr.com\nhttp://shadyrecords.com\nhttp://facebook.com/shadyrecords\nhttp://twitter.com/shadyrecords\nhttp://instagram.com/shadyrecords\nhttp://trustshady.tumblr.com\n\nMusic video by Eminem performing Walk On Water. (C) 2017 Aftermath Records\nhttp://vevo.ly/gA7xKt  n1WpP7iowLc       EminemVEVO            10.0  2017-11-10T17:00:03.000Z                                            Eminem|"Walk"|"On"|"Water"|"Aftermath/Shady/Interscope"|"Rap"  17158579.0   787420.0      43420.0          125882.0  https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg                False               False                     False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Eminem's new track Walk on Water ft. Beyoncé is available everywhere: http://shady.sr/WOWEminem \nPlaylist Best of Eminem: https://goo.gl/AquNpo\nSubscribe for more: https://goo.gl/DxCrDV\n\nFor more visit: \nhttp://eminem.com\nhttp://facebook.com/eminem\nhttp://twitter.com/eminem\nhttp://instagram.com/eminem\nhttp://eminem.tumblr.com\nhttp://shadyrecords.com\nhttp://facebook.com/shadyrecords\nhttp://twitter.com/shadyrecords\nhttp://instagram.com/shadyrecords\nhttp://trustshady.tumblr.com\n\nMusic video by Eminem performing Walk On Water. (C) 2017 Aftermath Records\nhttp://vevo.ly/gA7xKt
PLUSH - Bad Unboxing Fan Mail                         17.14.11       0dBIkQ4Mz1M         iDubbbzTV               23  2017-11-13T17:00:00.000Z                                                                                                                                                                                                   plush|"bad unboxing"|"unboxing"|"fan mail"|"idubbbztv"|"idubbbztv2"|"things"|"best"|"packages"|"plushies"|"chontent chop"    1014651     127794          1688              13030  https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg                  False                 False                       False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    STill got a lot of packages. Probably will last for another year. On a side note, more 2nd channel vids soon. editing with premiere from now on, gon' be a tedious transition, but i think it's for the best. \n\n__\n\nSUBSCRIBE ► http://www.youtube.com/subscription_center?add_user=iDubbbztv\n\nMain Channel ► https://www.youtube.com/user/iDubbbzTV\nSecond Channel ► https://www.youtube.com/channel/UC-tsNNJ3yIW98MtPH6PWFAQ\nGaming Channel ► https://www.youtube.com/channel/UCVhfFXNY0z3-mbrTh1OYRXA\n\nWebsite ► http://www.idubbbz.com/\n\nInstagram ► https://instagram.com/idubbbz/\nTwitter ► https://twitter.com/Idubbbz\nFacebook ► http://www.facebook.com/IDubbbz\nTwitch ► http://www.twitch.tv/idubbbz\n_          NaN              NaN             NaN                       NaN                                                                                                      NaN         NaN        NaN          NaN               NaN                                             NaN                  NaN                 NaN                       NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 NaN
Racist Superman | Rudy Mancuso, King Bach & Lele Pons 17.14.11       5qpjK5DgCt4      Rudy Mancuso               23  2017-11-12T19:05:24.000Z  racist superman|"rudy"|"mancuso"|"king"|"bach"|"racist"|"superman"|"love"|"rudy mancuso poo bear black white official music video"|"iphone x by pineapple"|"lelepons"|"hannahstocking"|"rudymancuso"|"inanna"|"anwar"|"sarkis"|"shots"|"shotsstudios"|"alesso"|"anitta"|"brazil"|"Getting My Driver's License | Lele Pons"    3191434     146035          5339               8181  https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg                  False                 False                       False                                                                           WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► https://www.youtube.com/channel/UC5jkXpfnBhlDjqh0ir5FsIQ?sub_confirmation=1\n\nTHANKS FOR WATCHING! LIKE & SUBSCRIBE FOR MORE VIDEOS!\n-----------------------------------------------------------\nFIND ME ON: \nInstagram | http://instagram.com/rudymancuso\nTwitter | http://twitter.com/rudymancuso\nFacebook | http://facebook.com/rudymancuso\n\nCAST: \nRudy Mancuso | http://youtube.com/c/rudymancuso\nLele Pons | http://youtube.com/c/lelepons\nKing Bach | https://youtube.com/user/BachelorsPadTv\n\nVideo Effects: \nCaleb Natale | https://instagram.com/calebnatale\n\nPA:\nPaulina Gregory\n\n\nShots Studios Channels:\nAlesso | https://youtube.com/c/alesso\nAnitta | http://youtube.com/c/anitta\nAnwar Jibawi | http://youtube.com/c/anwar\nAwkward Puppets | http://youtube.com/c/awkwardpuppets\nHannah Stocking | http://youtube.com/c/hannahstocking\nInanna Sarkis | http://youtube.com/c/inanna\nLele Pons | http://youtube.com/c/lelepons\nMaejor | http://youtube.com/c/maejor\nMike Tyson | http://youtube.com/c/miketyson \nRudy Mancuso | http://youtube.com/c/rudymancuso\nShots Studios | http://youtube.com/c/shots\n\n#Rudy\n#RudyMancuso          NaN              NaN             NaN                       NaN                                                                                                      NaN         NaN        NaN          NaN               NaN                                             NaN                  NaN                 NaN                       NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 NaN
I Dare You: GOING BALD!?                              17.14.11       d380meD0W0M          nigahiga               24  2017-11-12T18:01:41.000Z                                                                                                                                                                                                    ryan|"higa"|"higatv"|"nigahiga"|"i dare you"|"idy"|"rhpc"|"dares"|"no truth"|"comments"|"comedy"|"funny"|"stupid"|"fail"    2095828     132239          1989              17518  https://i.ytimg.com/vi/d380meD0W0M/default.jpg                  False                 False                       False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        I know it's been a while since we did this show, but we're back with what might be the best episode yet!\nLeave your dares in the comment section! \n\nOrder my book how to write good \nhttp://higatv.com/ryan-higas-how-to-write-good-pre-order-links/\n\nJust Launched New Official Store\nhttps://www.gianthugs.com/collections/ryan\n\nHigaTV Channel\nhttp://www.youtube.com/higatv\n\nTwitter\nhttp://www.twitter.com/therealryanhiga\n\nFacebook\nhttp://www.facebook.com/higatv\n\nWebsite\nhttp://www.higatv.com\n\nInstagram\nhttp://www.instagram.com/notryanhiga\n\nSend us mail or whatever you want here!\nPO Box 232355\nLas Vegas, NV 89105          NaN              NaN             NaN                       NaN                                                                                                      NaN         NaN        NaN          NaN               NaN                                             NaN                  NaN                 NaN                       NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 NaN

## 1.
`region_1` and `region_2` are pretty uninformative names for locale columns in the dataset. Create a copy of `reviews` with these columns renamed to region` and `locale`, respectively.

In [159]:
renamed = reviews.rename(columns={'region_1': 'region', 'region_2': 'locale'})

In [160]:
renamed.head()

fields,country,description,designation,points,price,province,region,locale,taster_name,taster_twitter_handle,title,variety,winery
wines,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,Unknown,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

## 3.
        The [Things on Reddit] dataset includes product links from a selection of top-ranked forums ("subreddits") on reddit.com. Run the cell below to load a dataframe of products mentioned on the */r/gaming* subreddit and another dataframe for products mentioned on the *r//movies* subreddit.

In [161]:
gaming_products = pd.read_csv('testing_dataset/gaming.csv')

In [162]:
movie_products = pd.read_csv('testing_dataset/movies.csv')

In [163]:
gaming_products.head()

,name,category,amazon_link,total_mentions,subreddit_mentions
0,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4
1,Raspberry PI 3 Model B 1.2GHz 64-bit quad-core...,Electronics,https://www.amazon.com/Raspberry-Model-A1-2GHz...,19.0,3
2,CanaKit 5V 2.5A Raspberry Pi 3 Power Supply / ...,Electronics,https://www.amazon.com/CanaKit-Raspberry-Suppl...,7.0,3
3,Panasonic K-KJ17MCA4BA Advanced Individual Cel...,Electronics,https://www.amazon.com/Panasonic-Advanced-Indi...,29.0,2
4,Mayflash GameCube Controller Adapter for Wii U...,Electronics,https://www.amazon.com/GameCube-Controller-Ada...,24.0,2

In [164]:
movie_products.head()

,name,category,amazon_link,total_mentions,subreddit_mentions
0,Marvel Cinematic Universe: Phase One - Avenger...,Movies & TV,https://www.amazon.com/Marvel-Cinematic-Univer...,4.0,3
1,On Stranger Tides,Books,https://www.amazon.com/Stranger-Tides-Tim-Powe...,3.0,3
2,"Superintelligence: Paths, Dangers, Strategies",Books,https://www.amazon.com/Superintelligence-Dange...,7.0,2
3,The Secret History of Star Wars,Books,https://www.amazon.com/Secret-History-Star-War...,4.0,2
4,2D Glasses 4 Pack - Turns 3D movies back into ...,Electronics,https://www.amazon.com/gp/product/B00K9E7GCC,3.0,2

In [165]:
pd.concat([gaming_products, movie_products])
# combine two DataFrames by stacking rows, join gaming products on top of movie products

,name,category,amazon_link,total_mentions,subreddit_mentions
0,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4
1,Raspberry PI 3 Model B 1.2GHz 64-bit quad-core...,Electronics,https://www.amazon.com/Raspberry-Model-A1-2GHz...,19.0,3
2,CanaKit 5V 2.5A Raspberry Pi 3 Power Supply / ...,Electronics,https://www.amazon.com/CanaKit-Raspberry-Suppl...,7.0,3
3,Panasonic K-KJ17MCA4BA Advanced Individual Cel...,Electronics,https://www.amazon.com/Panasonic-Advanced-Indi...,29.0,2
4,Mayflash GameCube Controller Adapter for Wii U...,Electronics,https://www.amazon.com/GameCube-Controller-Ada...,24.0,2
...,...,...,...,...,...
298,Welcome to Night Vale CD: A Novel,Books,https://www.amazon.com/Welcome-Night-Vale-CD-N...,1.0,1
299,Ran (StudioCanal Collection) [Blu-ray],Movies & TV,https://www.amazon.com/StudioCanal-Collection-...,1.0,1
300,The Art of John Alvin,Books,https://www.amazon.com/Art-John-Alvin-Andrea/d...,1.0,1
301,Apocalypto [Blu-ray],Movies & TV,https://www.amazon.com/Apocalypto-Blu-ray-Rudy...,1.0,1
302,Cinelinx: A Card Game for People Who Love Movi...,Toys & Games,https://www.amazon.com/Cinelinx-Card-Game-Peop...,1.0,1