In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('stock_exchange_data/indexData.csv')

In [3]:
df.head()

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

In [4]:
df.tail()

,Index,Date,Open,High,Low,Close,Adj Close,Volume
112452,N100,2021-05-27,1241.119995,1251.910034,1241.119995,1247.069946,1247.069946,379696400.0
112453,N100,2021-05-28,1249.469971,1259.209961,1249.030029,1256.599976,1256.599976,160773400.0
112454,N100,2021-05-31,1256.079956,1258.880005,1248.140015,1248.930054,1248.930054,91173700.0
112455,N100,2021-06-01,1254.609985,1265.660034,1254.609985,1258.579956,1258.579956,155179900.0
112456,N100,2021-06-02,1258.489990,1263.709961,1258.239990,1263.619995,1263.619995,148465000.0

In [5]:
df.index # return the actualy index range

RangeIndex(start=0, stop=112457, step=1)

In [6]:
df.Index # return the index series

0          NYA
1          NYA
2          NYA
3          NYA
4          NYA
          ...
112452    N100
112453    N100
112454    N100
112455    N100
112456    N100
Name: Index, Length: 112457, dtype: object

In [7]:
df['Index']

0          NYA
1          NYA
2          NYA
3          NYA
4          NYA
          ...
112452    N100
112453    N100
112454    N100
112455    N100
112456    N100
Name: Index, Length: 112457, dtype: object

In [8]:
df['Index'][0]

'NYA'

## iloc

- Index-based Selection

    Both loc and iloc are row-first, column-second. This is the opposite of what we do in native Python, which is column-first, row-second.

    This means that it's marginally easier to retrieve rows, and marginally harder to get retrieve columns.

In [9]:
df.iloc[0] # retrieve the row at index 0

Index               NYA
Date         1965-12-31
Open         528.690002
High         528.690002
Low          528.690002
Close        528.690002
Adj Close    528.690002
Volume              0.0
Name: 0, dtype: object

In [10]:
df.iloc[:, 1] # retrieve all rows (all indexes), at column 1

0         1965-12-31
1         1966-01-03
2         1966-01-04
3         1966-01-05
4         1966-01-06
             ...
112452    2021-05-27
112453    2021-05-28
112454    2021-05-31
112455    2021-06-01
112456    2021-06-02
Name: Date, Length: 112457, dtype: object

In [11]:
df.iloc[:3, 1] # retrieve first 3 rows, at column 1

0    1965-12-31
1    1966-01-03
2    1966-01-04
Name: Date, dtype: object

In [12]:
df.iloc[[1, 2, 3, 4], 1] # retrieve all rows in the index list, at column 1

1    1966-01-03
2    1966-01-04
3    1966-01-05
4    1966-01-06
Name: Date, dtype: object

In [13]:
df.tail()

,Index,Date,Open,High,Low,Close,Adj Close,Volume
112452,N100,2021-05-27,1241.119995,1251.910034,1241.119995,1247.069946,1247.069946,379696400.0
112453,N100,2021-05-28,1249.469971,1259.209961,1249.030029,1256.599976,1256.599976,160773400.0
112454,N100,2021-05-31,1256.079956,1258.880005,1248.140015,1248.930054,1248.930054,91173700.0
112455,N100,2021-06-01,1254.609985,1265.660034,1254.609985,1258.579956,1258.579956,155179900.0
112456,N100,2021-06-02,1258.489990,1263.709961,1258.239990,1263.619995,1263.619995,148465000.0

In [14]:
df.iloc[-5:] # retrieve last 5 indexes, equivalent to tail()

,Index,Date,Open,High,Low,Close,Adj Close,Volume
112452,N100,2021-05-27,1241.119995,1251.910034,1241.119995,1247.069946,1247.069946,379696400.0
112453,N100,2021-05-28,1249.469971,1259.209961,1249.030029,1256.599976,1256.599976,160773400.0
112454,N100,2021-05-31,1256.079956,1258.880005,1248.140015,1248.930054,1248.930054,91173700.0
112455,N100,2021-06-01,1254.609985,1265.660034,1254.609985,1258.579956,1258.579956,155179900.0
112456,N100,2021-06-02,1258.489990,1263.709961,1258.239990,1263.619995,1263.619995,148465000.0

## loc

- Label-based selection

    The second paradigm for attribute selection is the one followed by the loc operator: label-based selection. In this paradigm, it's the data index value, not its position, which matters.

In [15]:
df.loc[:5, 'Date'] # retrieve first 6 rows, at 'Date' column

0    1965-12-31
1    1966-01-03
2    1966-01-04
3    1966-01-05
4    1966-01-06
5    1966-01-07
Name: Date, dtype: object

In [16]:
df.loc[-5:, ['Date', 'Open', 'Volume']] # this actually returns all rows because negative slicing is not supported in loc

              Date         Open       Volume
0       1965-12-31   528.690002          0.0
1       1966-01-03   527.210022          0.0
2       1966-01-04   527.840027          0.0
3       1966-01-05   531.119995          0.0
4       1966-01-06   532.070007          0.0
...            ...          ...          ...
112452  2021-05-27  1241.119995  379696400.0
112453  2021-05-28  1249.469971  160773400.0
112454  2021-05-31  1256.079956   91173700.0
112455  2021-06-01  1254.609985  155179900.0
112456  2021-06-02  1258.489990  148465000.0

[112457 rows x 3 columns]

## Choosing between loc and iloc

    When choosing or transitioning between loc and iloc, there is one "gotcha" worth keeping in mind, which is that the two methods use slightly different indexing schemes.

    iloc uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. So 0:10 will select entries 0,...,9. loc, meanwhile, indexes inclusively. So 0:10 will select entries 0,...,10.

    Why the change? Remember that loc can index any stdlib type: strings, for example. If we have a DataFrame with index values Apples, ..., Potatoes, ..., and we want to select "all the alphabetical fruit choices between Apples and Potatoes", then it's a lot more convenient to index df.loc['Apples':'Potatoes'] than it is to index something like df.loc['Apples', 'Potatoet'] (t coming after s in the alphabet).

    This is particularly confusing when the DataFrame index is a simple numerical list, e.g. 0,...,1000. In this case df.iloc[0:1000] will return 1000 entries, while df.loc[0:1000] return 1001 of them! To get 1000 elements using loc, you will need to go one lower and ask for df.loc[0:999].

    Otherwise, the semantics of using loc are the same as those for iloc.

In [17]:
sf = pd.DataFrame({'Stock':['Apple', 'Google', 'OpenAI', 'Celsius', 'TIKTAK', 'META', 'HNG', 'XKJ', 'Alani'], 'Price':[100, 320, 482, 883, 432, 399, 732, None, 883], 'Location':['USA', 'CAN', 'CHIL', 'UAE', 'KOR', 'SEB', 'CHI', 'JAP', 'PHI'], 'ETF':['Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y'], 'Valid': [None, None, None, None, None, None, None, None, None], 'Shares': [139, 421, 123, 93, 212, 194, 283, 333, 93]})

In [18]:
sf.set_index('Stock', inplace=True) # set index to 'Stock' column, modifying the original DataFrame index

In [19]:
sf.head() # Stock is the indexing column for the DataFrame

         Price Location ETF Valid  Shares
Stock
Apple    100.0      USA   Y  None     139
Google   320.0      CAN   Y  None     421
OpenAI   482.0     CHIL   N  None     123
Celsius  883.0      UAE   N  None      93
TIKTAK   432.0      KOR   Y  None     212

In [20]:
sf.loc['Google':'TIKTAK', ['Location', 'ETF', 'Shares']]  
# retrieve rows from 'Google' to 'TIKTAK', at 'Location' and 'ETF' columns

        Location ETF  Shares
Stock
Google       CAN   Y     421
OpenAI      CHIL   N     123
Celsius      UAE   N      93
TIKTAK       KOR   Y     212

## Conditional Selection

In [21]:
sf.Price > 400  # boolean mask for rows where Price is greater than 400, return a series of True/False

Stock
Apple      False
Google     False
OpenAI      True
Celsius     True
TIKTAK      True
META       False
HNG         True
XKJ        False
Alani       True
Name: Price, dtype: bool

In [22]:
sf.loc[sf['Price'] > 400, :] 
# sf['Price'] > 400 is a series of True/False values indicating whether each row meets the condition, if true the row is included in the result
# in the series of true/false values, if True, the corresponding row is included in the output DataFrame

         Price Location ETF Valid  Shares
Stock
OpenAI   482.0     CHIL   N  None     123
Celsius  883.0      UAE   N  None      93
TIKTAK   432.0      KOR   Y  None     212
HNG      732.0      CHI   Y  None     283
Alani    883.0      PHI   Y  None      93

In [23]:
sf.loc[(sf['Price'] > 300) & (sf['ETF'] == 'Y'), ['Location', 'Price', 'ETF']]
# retrieve rows where Price is greater than 300 and ETF is 'Y', at 'Location', 'Price', and 'ETF' columns
# the result this conditonal filtering is from two series of True/False values combined with the & operator

       Location  Price ETF
Stock
Google      CAN  320.0   Y
TIKTAK      KOR  432.0   Y
META        SEB  399.0   Y
HNG         CHI  732.0   Y
Alani       PHI  883.0   Y

In [24]:
sf['Price'] > 399

Stock
Apple      False
Google     False
OpenAI      True
Celsius     True
TIKTAK      True
META       False
HNG         True
XKJ        False
Alani       True
Name: Price, dtype: bool

In [25]:
sf[sf['Price'] > 399] # return a dataframe with only rows where Price is greater than 399

         Price Location ETF Valid  Shares
Stock
OpenAI   482.0     CHIL   N  None     123
Celsius  883.0      UAE   N  None      93
TIKTAK   432.0      KOR   Y  None     212
HNG      732.0      CHI   Y  None     283
Alani    883.0      PHI   Y  None      93

In [26]:
sf.loc[sf['Location'].isin(['CHI', 'JAP', 'USA'])] 
# return a dataframe with rows where Location is either 'CHI', 'JAP', or 'USA'

       Price Location ETF Valid  Shares
Stock
Apple  100.0      USA   Y  None     139
HNG    732.0      CHI   Y  None     283
XKJ      NaN      JAP   N  None     333

In [27]:
sf.loc[sf.Price.notnull()]  # return a dataframe with rows where Price is not null

         Price Location ETF Valid  Shares
Stock
Apple    100.0      USA   Y  None     139
Google   320.0      CAN   Y  None     421
OpenAI   482.0     CHIL   N  None     123
Celsius  883.0      UAE   N  None      93
TIKTAK   432.0      KOR   Y  None     212
META     399.0      SEB   Y  None     194
HNG      732.0      CHI   Y  None     283
Alani    883.0      PHI   Y  None      93

## Markdown Notes:

    iloc vs loc

- iloc 'looking at the position at that index'
- loc 'looks up the index, look for a specific entry'

## Assign

In [28]:
sf['Valid'] = 67 # assign all rows in the series 'Valid' to 67

In [29]:
sf.loc[sf.index == 'Apple', 'Price'] = 1010 
# set the 'Price' for the row with index 'Apple' to 1010

In [30]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Apple    1010.0      USA   Y     67     139
Google    320.0      CAN   Y     67     421
OpenAI    482.0     CHIL   N     67     123
Celsius   883.0      UAE   N     67      93
TIKTAK    432.0      KOR   Y     67     212
META      399.0      SEB   Y     67     194
HNG       732.0      CHI   Y     67     283
XKJ         NaN      JAP   N     67     333
Alani     883.0      PHI   Y     67      93

In [31]:
sf.iloc[2:7, 0] # this is a series, return only price series

Stock
OpenAI     482.0
Celsius    883.0
TIKTAK     432.0
META       399.0
HNG        732.0
Name: Price, dtype: float64

In [32]:
sf.iloc[2:7, :1] # slices return a dataframe

         Price
Stock
OpenAI   482.0
Celsius  883.0
TIKTAK   432.0
META     399.0
HNG      732.0

In [33]:
sf.loc['OpenAI':'HNG', 'Valid'] = 9999 
# from 'OpenAI' to 'HNG' rows, assign the value 9999 to the 'Valid' column

In [34]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Apple    1010.0      USA   Y     67     139
Google    320.0      CAN   Y     67     421
OpenAI    482.0     CHIL   N   9999     123
Celsius   883.0      UAE   N   9999      93
TIKTAK    432.0      KOR   Y   9999     212
META      399.0      SEB   Y   9999     194
HNG       732.0      CHI   Y   9999     283
XKJ         NaN      JAP   N     67     333
Alani     883.0      PHI   Y     67      93

In [35]:
sf['Valid'] = range(len(sf), 0, -1) 
# len(sf) returns the number of rows in the DataFrame, so this assigns a descending range of values to the 'Valid' column

In [36]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Apple    1010.0      USA   Y      9     139
Google    320.0      CAN   Y      8     421
OpenAI    482.0     CHIL   N      7     123
Celsius   883.0      UAE   N      6      93
TIKTAK    432.0      KOR   Y      5     212
META      399.0      SEB   Y      4     194
HNG       732.0      CHI   Y      3     283
XKJ         NaN      JAP   N      2     333
Alani     883.0      PHI   Y      1      93

In [37]:
sf.sort_values(by='Price', inplace=True)

In [38]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      8     421
META      399.0      SEB   Y      4     194
TIKTAK    432.0      KOR   Y      5     212
OpenAI    482.0     CHIL   N      7     123
HNG       732.0      CHI   Y      3     283
Celsius   883.0      UAE   N      6      93
Alani     883.0      PHI   Y      1      93
Apple    1010.0      USA   Y      9     139
XKJ         NaN      JAP   N      2     333

In [39]:
sf.sort_values(by='Valid').loc[:, ['Price', 'Valid']] 
# sort by 'Valid' column and return the 'Price' column

          Price  Valid
Stock
Alani     883.0      1
XKJ         NaN      2
HNG       732.0      3
META      399.0      4
TIKTAK    432.0      5
Celsius   883.0      6
OpenAI    482.0      7
Google    320.0      8
Apple    1010.0      9

In [40]:
print(sf)

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      8     421
META      399.0      SEB   Y      4     194
TIKTAK    432.0      KOR   Y      5     212
OpenAI    482.0     CHIL   N      7     123
HNG       732.0      CHI   Y      3     283
Celsius   883.0      UAE   N      6      93
Alani     883.0      PHI   Y      1      93
Apple    1010.0      USA   Y      9     139
XKJ         NaN      JAP   N      2     333

In [41]:
max_price = sf['Price'] < 600
type = sf['ETF'].isin(['Y'])

sf.loc[max_price & type, :]

        Price Location ETF  Valid  Shares
Stock
Google  320.0      CAN   Y      8     421
META    399.0      SEB   Y      4     194
TIKTAK  432.0      KOR   Y      5     212

## Summary of Functions / Maps


        However, the data does not always come out of memory in the format we want it in right out of the bat. Sometimes we have to do some more work ourselves to reformat it for the task at hand. This tutorial will cover different operations we can apply to our data to get the input "just right".

In [42]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      8     421
META      399.0      SEB   Y      4     194
TIKTAK    432.0      KOR   Y      5     212
OpenAI    482.0     CHIL   N      7     123
HNG       732.0      CHI   Y      3     283
Celsius   883.0      UAE   N      6      93
Alani     883.0      PHI   Y      1      93
Apple    1010.0      USA   Y      9     139
XKJ         NaN      JAP   N      2     333

In [43]:
sf.describe() # returns a dataframe with statistical summary of all numeric columns

             Price     Valid      Shares
count     8.000000  9.000000    9.000000
mean    642.625000  5.000000  210.111111
std     265.145748  2.738613  114.688104
min     320.000000  1.000000   93.000000
25%     423.750000  3.000000  123.000000
50%     607.000000  5.000000  194.000000
75%     883.000000  7.000000  283.000000
max    1010.000000  9.000000  421.000000

In [44]:
sf.Price.describe() # returns a series with statistical summary of the 'Price' column

count       8.000000
mean      642.625000
std       265.145748
min       320.000000
25%       423.750000
50%       607.000000
75%       883.000000
max      1010.000000
Name: Price, dtype: float64

In [45]:
sf.Price.mean() # returns the mean of the 'Price' column

np.float64(642.625)

In [46]:
sf.Location.unique() # returns an array of unique values in the 'array' column

array(['CAN', 'SEB', 'KOR', 'CHIL', 'CHI', 'UAE', 'PHI', 'USA', 'JAP'],
      dtype=object)

In [47]:
sf.ETF.value_counts() # returns a series with counts of unique values in the 'ETF' column

ETF
Y    6
N    3
Name: count, dtype: int64

# **Pandas Testing**

In [49]:
sf.count() # count non-null entries for each column

Price       8
Location    9
ETF         9
Valid       9
Shares      9
dtype: int64

In [50]:
price_mean = sf.Price.mean() # returns the mean of the 'Price' column

print('Price Mean:', price_mean)

sf.Price.map(lambda x: x - price_mean) 
# return a series of the form (current index value - mean) for each index in the 'Price' column

Price Mean: 642.625

Stock
Google    -322.625
META      -243.625
TIKTAK    -210.625
OpenAI    -160.625
HNG         89.375
Celsius    240.375
Alani      240.375
Apple      367.375
XKJ            NaN
Name: Price, dtype: float64

In [51]:
import random

def randrow(row):
    row.Valid = random.randint(0, 10)
    return row

sf.apply(randrow, axis=1) # this does not modify the original DataFrame

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      1     421
META      399.0      SEB   Y      5     194
TIKTAK    432.0      KOR   Y      1     212
OpenAI    482.0     CHIL   N      9     123
HNG       732.0      CHI   Y     10     283
Celsius   883.0      UAE   N      9      93
Alani     883.0      PHI   Y      2      93
Apple    1010.0      USA   Y      0     139
XKJ         NaN      JAP   N      5     333

In [53]:
sf.sum(axis=0, numeric_only=True) # sum of all numeric columns, axis=0 means summing down the rows for each column

Price     5141.0
Valid       45.0
Shares    1891.0
dtype: float64

In [54]:
sf.sum(axis=1, numeric_only=True) # sum of all numeric columns, axis=1 means summing across the columns for each row

Stock
Google      749.0
META        597.0
TIKTAK      649.0
OpenAI      612.0
HNG        1018.0
Celsius     982.0
Alani       977.0
Apple      1158.0
XKJ         335.0
dtype: float64

In [55]:
randrow(sf) # this modifies the original DataFrame 
# called with the whole DataFrame (row is the DataFrame)
# mutates sf in-place because you passed the DataFrame

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      9     421
META      399.0      SEB   Y      9     194
TIKTAK    432.0      KOR   Y      9     212
OpenAI    482.0     CHIL   N      9     123
HNG       732.0      CHI   Y      9     283
Celsius   883.0      UAE   N      9      93
Alani     883.0      PHI   Y      9      93
Apple    1010.0      USA   Y      9     139
XKJ         NaN      JAP   N      9     333

In [56]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      9     421
META      399.0      SEB   Y      9     194
TIKTAK    432.0      KOR   Y      9     212
OpenAI    482.0     CHIL   N      9     123
HNG       732.0      CHI   Y      9     283
Celsius   883.0      UAE   N      9      93
Alani     883.0      PHI   Y      9      93
Apple    1010.0      USA   Y      9     139
XKJ         NaN      JAP   N      9     333

In [57]:
sf.Valid = range(len(sf), 0, -1) # revert values back

In [58]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      9     421
META      399.0      SEB   Y      8     194
TIKTAK    432.0      KOR   Y      7     212
OpenAI    482.0     CHIL   N      6     123
HNG       732.0      CHI   Y      5     283
Celsius   883.0      UAE   N      4      93
Alani     883.0      PHI   Y      3      93
Apple    1010.0      USA   Y      2     139
XKJ         NaN      JAP   N      1     333

In [59]:
sf.Price - price_mean # built in mapping operation

Stock
Google    -322.625
META      -243.625
TIKTAK    -210.625
OpenAI    -160.625
HNG         89.375
Celsius    240.375
Alani      240.375
Apple      367.375
XKJ            NaN
Name: Price, dtype: float64

In [60]:
sf.Location + " - " + sf.ETF # concatenate strings from 'Location' and 'ETF' columns with " - " in between

Stock
Google      CAN - Y
META        SEB - Y
TIKTAK      KOR - Y
OpenAI     CHIL - N
HNG         CHI - Y
Celsius     UAE - N
Alani       PHI - Y
Apple       USA - Y
XKJ         JAP - N
dtype: object

In [62]:
sf.Price.median()

np.float64(607.0)

### Find Best Price to Share Ratio

In [63]:
price_to_share_ratio = sf.Price/sf.Shares # price to share ratio for each stock
print(price_to_share_ratio)

Stock
Google     0.760095
META       2.056701
TIKTAK     2.037736
OpenAI     3.918699
HNG        2.586572
Celsius    9.494624
Alani      9.494624
Apple      7.266187
XKJ             NaN
dtype: float64

In [64]:
highest_stock1 = sf.apply(lambda x: x.Price/x.Shares, axis=1).sort_values(ascending=False).index[0] 
# returns the index of the stock with the highest price to share ratio
print(highest_stock1)

Alani

In [65]:
highest_stock2 = price_to_share_ratio.idxmax() # returns the index of the maximum value in the series
print(highest_stock2)

Celsius

In [66]:
print(sf.to_string())

          Price Location ETF  Valid  Shares
Stock
Google    320.0      CAN   Y      9     421
META      399.0      SEB   Y      8     194
TIKTAK    432.0      KOR   Y      7     212
OpenAI    482.0     CHIL   N      6     123
HNG       732.0      CHI   Y      5     283
Celsius   883.0      UAE   N      4      93
Alani     883.0      PHI   Y      3      93
Apple    1010.0      USA   Y      2     139
XKJ         NaN      JAP   N      1     333

In [144]:
sf.reset_index(inplace=True) # set index back to default integer index
print(sf)

   index    Stock   Price Location ETF  Valid  Shares
0      0   Google   320.0      CAN   Y      9     421
1      1     META   399.0      SEB   Y      8     194
2      2   TIKTAK   432.0      KOR   Y      7     212
3      3   OpenAI   482.0     CHIL   N      6     123
4      4      HNG   732.0      CHI   Y      5     283
5      5  Celsius   883.0      UAE   N      4      93
6      6    Alani   883.0      PHI   Y      3      93
7      7    Apple  1010.0      USA   Y      2     139
8      8      XKJ     NaN      JAP   N      1     333

In [ ]:
max_ratio = sf.dropna(subset=['Price', 'Shares']).loc[:, ['Price', 'Shares']].apply(lambda x: x.Price/x.Shares, axis=1).max()
mask = (sf.Price/sf.Shares) == max_ratio
sf.loc[mask,:]
# retrieve the row(s) with the highest price to share ratio

   index    Stock  Price Location ETF  Valid  Shares
5      5  Celsius  883.0      UAE   N      4      93
6      6    Alani  883.0      PHI   Y      3      93

### Pandas Testing on Wine Reviews Dataset

In [69]:
import string
reviews = pd.read_csv('wine_dataset/winemag-data-130k-v2.csv', index_col=0)

In [70]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

#### Extract Counts of 'tropical'/'fruity' in Description Column

In [71]:
freq = {'tropical':0, 'fruity':0}
desc = [word.strip(string.punctuation).lower() for word in reviews.description[0].split()]
print(desc)
print(desc.count('tropical'))

['aromas', 'include', 'tropical', 'fruit', 'broom', 'brimstone', 'and', 'dried', 'herb', 'the', 'palate', "isn't", 'overly', 'expressive', 'offering', 'unripened', 'apple', 'citrus', 'and', 'dried', 'sage', 'alongside', 'brisk', 'acidity']
1

In [72]:
for word in desc:  
   if word in freq:
      freq[word] += 1

print(freq)

{'tropical': 1, 'fruity': 0}

In [73]:
tf = pd.DataFrame(data=freq, index=[0])

In [74]:
print(tf)

   tropical  fruity
0         1       0

In [75]:
reviews.description.head()

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
2    Tart and snappy, the flavors of lime flesh and...
3    Pineapple rind, lemon pith and orange blossom ...
4    Much like the regular bottling from 2012, this...
Name: description, dtype: object

In [76]:
def frequency(desc):
    filter_desc = [word.strip(string.punctuation).lower() for word in desc.description.split()]
    tropical_count = filter_desc.count('tropical')
    fruit_count = filter_desc.count('fruity')
    return tropical_count, fruit_count

x = reviews.apply(frequency, axis=1)
print(x)

0         (1, 0)
1         (0, 1)
2         (0, 0)
3         (0, 0)
4         (0, 0)
           ...
129966    (0, 0)
129967    (0, 0)
129968    (0, 1)
129969    (0, 0)
129970    (0, 0)
Length: 129971, dtype: object

In [77]:
y = x.map(lambda x: x[0]).sum(axis=0)

print(y)

3638

In [78]:
z = x.map(lambda x: x[1]).sum(axis=0)

print(z)

9466

In [82]:
pd.Series([y, z], index=['tropical', 'fruity'])

tropical    3638
fruity      9466
dtype: int64

In [81]:
tropical_count = reviews.description.map(lambda x: 'tropical' in x).sum() 
# count of reviews containing the word 'tropical', if true, counts as 1
fruity_count = reviews.description.map(lambda x: 'fruity' in x).sum()
# count of reviews containing the word 'fruity', if true, counts as 1

descriptor_count = pd.Series([tropical_count, fruity_count], index=['tropical', 'fruity'])
#return a series with index as the descriptor names and values as their respective counts

print(descriptor_count)

tropical    3607
fruity      9090
dtype: int64

### Star rating based on points and country

In [91]:
def wrapper(row):
    if ((row.points >= 95) & (row.country != 'Canada')) or (row.country == 'Canada'):
        return 3
    elif (row.points >= 85) & (row.country != 'Canada'):
        return 2
    else:
        return 1

star_ratings = reviews.apply(wrapper, axis=1)

print(star_ratings.value_counts())

2    114877
1     12421
3      2673
Name: count, dtype: int64

## Grouping and Sorting

        However, often we want to group our data, and then do something specific to the group the data is in.

        As you'll learn, we do this with the groupby() operation. We'll also cover some additional topics, such as more complex ways to index your DataFrames, along with how to sort your data.

In [92]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
reviews.groupby('points').points.count() # count of reviews for each unique point value
# this is the same as review.points.value_counts().sort_index()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [ ]:
result = reviews.groupby('points').price.sum()

In [ ]:
display(result.head())

points
80      6467.0
81     11684.0
82     33439.0
83     52633.0
84    117773.0
Name: price, dtype: float64

In [388]:
reviews.groupby('points').price.min() # cheapest wine in each point category

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

In [ ]:
reviews.groupby('points').price.max() # most expensive wine in each point category

points
80       69.0
81      130.0
82      150.0
83      225.0
84      225.0
85      320.0
86      170.0
87      800.0
88     3300.0
89      500.0
90      510.0
91     2013.0
92      750.0
93      770.0
94     1125.0
95      973.0
96     2500.0
97     2000.0
98     1900.0
99      850.0
100    1500.0
Name: price, dtype: float64

In [151]:
for key, df in reviews.groupby('points'):
    print('Group:', key)
    print(df.to_string())
    break

Group: 80
            country                                                                                                                                                                                                                                                                                                                                                                                              description                                       designation  points  price                         province                              region_1           region_2         taster_name taster_twitter_handle                                                                                               title                        variety                                  winery
344           Chile                                                                                                                                                                                  Aromas of pumpkin, squash and corn chips are stale and not inviting. There's an acceptable mouthfeel to this weird, unbalanced Chardonnay along with flavors of spiced squash, mealy apple and sautéed root vegetables.                                      Gran Reserva      80   19.0                     Leyda Valley                                   NaN                NaN   Michael Schachner           @wineschach                                           Viña Tarapacá 2015 Gran Reserva Chardonnay (Leyda Valley)                     Chardonnay                           Viña Tarapacá
3640       Portugal                                                                                                                                                                                                                                                                      Aromas of strawberry sherbet are followed by sweet candy-shop flavors on the palate. Chill it thoroughly before drinking. Screwcap.                                           Estreia      80    8.0                      Vinho Verde                                   NaN                NaN          Roger Voss            @vossroger                                                           Viniverde 2011 Estreia Rosé (Vinho Verde)                           Rosé                               Viniverde
3641          Chile                                                                                                                                                                                                          Fluffy, sweet aromas of peach, pear and vanilla are as good as it gets. Tastes of powdered sugar and the most forced oak you can imagine. Not at all surprising that it's resiny on the finish.                                           Reserve      80   15.0                     Maule Valley                                   NaN                NaN   Michael Schachner           @wineschach                                               Cuevas del Sur 2010 Reserve Chardonnay (Maule Valley)                     Chardonnay                          Cuevas del Sur
4556          Italy                                                                                                                                                                                                                                                 There's a thorny, almost raw quality of fruit here that is backed by a touch of dill weed and black tar. It feels tart and slightly bitter on the close.                                         Rondineto      80   12.0                    Central Italy                        Colli Aprutini                NaN                 NaN                   NaN                                     Fattoria Giuseppe Savini 2011 Rondineto Merlot (Colli Aprutini)                         Merlot                Fattoria Giuseppe Savini
4557          Spain                                                                                                                                           With dusty, candied aromas, the bouquet on this semisweet Cava is scattered all over the map. In the mouth, it's inoffensive, however the wine's candied, melony flavors are cloying and overtly sugary. This is too clumsy and candied to be taken seriously.                                          Demi Sec      80   14.0                        Catalonia                                  Cava                NaN   Michael Schachner           @wineschach                                                           Paul Cheneau NV Demi Sec Sparkling (Cava)                Sparkling Blend                            Paul Cheneau
5905      Argentina                                                                                                                                                                                                                                                                                   Ashy, green and funky smelling, then sweet, chunky and murky tasting. Nothing is meshing here. It's barely acceptable.                                               NaN      80   17.0                 Mendoza Province                               Mendoza                NaN   Michael Schachner           @wineschach                                                      Bodega Carmine Granata 2009 Sémillon (Mendoza)                       Sémillon                  Bodega Carmine Granata
5906      Argentina                                                                                                                                                                                                           A rough, pinchy nose with leather and funk is no way to begin. The palate stays hard and spiky, with burnt, rustic, murky flavors. Roasted and mossy on the finish, and not very good overall.                                     Grand Reserve      80   20.0                 Mendoza Province                               Mendoza                NaN   Michael Schachner           @wineschach                                                       Cruz Alta 2007 Grand Reserve Malbec (Mendoza)                         Malbec                               Cruz Alta
5907      Argentina                                                                                                                                                                                                                                  Heavily vegetal and unclean on the nose, then pickled on the palate, as in sauerkraut. The only thing saving this from the flusher is decent body weight and mouthfeel.                                               NaN      80   15.0                 Mendoza Province                               Mendoza                NaN   Michael Schachner           @wineschach                                                              Ricardo Santos 2009 Sémillon (Mendoza)                       Sémillon                          Ricardo Santos
5908      Argentina                                                                                                                                                                                                                                                                                  Mute on the nose, but heavy in the mouth, with grapefruit and pickled flavors. Finishes pickled and pithy. Already old.                                               NaN      80   12.0                 Mendoza Province                               Mendoza                NaN   Michael Schachner           @wineschach                                                                     Gardel 2009 Torrontés (Mendoza)                      Torrontés                                  Gardel
5909      Argentina                                                                                                                                                                                                                 Medicinal and feral on the nose, then heavy, thick and extremely creamy and soft in the mouth, with bland, flat flavors of milk, carob and vanilla. Short on fruit, acidity and purpose.                                         Colección      80   12.0                 Mendoza Province                               Mendoza                NaN   Michael Schachner           @wineschach                                     Alma del Sur 2009 Colección Cabernet Sauvignon-Malbec (Mendoza)      Cabernet Sauvignon-Malbec                            Alma del Sur
7094      Argentina                                       The only thing that makes this a gran reserva is the label and the winery's commitment to a big, extracted, heavily oaked wine. It's black as ink but clumsy as can be. Smells and tastes like shoe polish, resin and oily fruit. Not what we're looking for from Argentina, or anywhere for that matter. Barely acceptable. Imported by Carolina Wine Brands USA.                                      Gran Reserva      80   18.0                 Mendoza Province                            Uco Valley                NaN   Michael Schachner           @wineschach                                               Finca El Origen 2007 Gran Reserva Malbec (Uco Valley)                         Malbec                         Finca El Origen
7095      Argentina                                                                                             This is the first Torrontés from Pascual Toso that we've rated, and if it's any indication of what's going on there, then we say stick to the reds. This is a borderline dud, with chunky, hollow flavors and a mealy finish. Not a total mess but not a good, vivacious Argentine Torrontes by any stretch.                                               NaN      80   12.0                 Mendoza Province                                 Maipú                NaN   Michael Schachner           @wineschach                                                                 Pascual Toso 2007 Torrontés (Maipú)                      Torrontés                            Pascual Toso
7096          Chile                                                                                                                                                      Having liked the 2007 rosé from Los Vascos, this pickled, citric burner just doesn't cut it. It shows Sauvignon Blanc-like flavors and acidity, while the finish is sour and briney. Devoid of the charm and pleasantries that rosé should deliver.                                        Los Vascos      80   12.0                 Colchagua Valley                                   NaN                NaN   Michael Schachner           @wineschach                      Domaines Barons de Rothschild (Lafite) 2008 Los Vascos Rosé (Colchagua Valley)                           Rosé  Domaines Barons de Rothschild (Lafite)
7332          Spain                                                                                                                                                                                                             Dry, dull papaya and apricot aromas surely don't overwhelm, but they don't foretell the complete lack of fruit on the palate. A faded, insipid white wine. It has no pulse and tastes mealy.                                               NaN      80   19.0                          Galicia                           Rías Baixas                NaN   Michael Schachner           @wineschach                                                                 Eleusis 2006 Albariño (Rías Baixas)                       Albariño                                 Eleusis
7333             US                                                                                                                                                                                                                                                                                  Too sweet by far for a table wine, with simple, medicinal cherry and blackberry flavors and a harshly tannic mouthfeel.                                               NaN      80   10.0                       California                            California   California Other                 NaN                   NaN                                                           Esser Cellars 2005 Zinfandel (California)                      Zinfandel                           Esser Cellars
7334             US                                                                                                                                                                                                                                                                                                        Excessively ripe fruit verging on baked, burnt blackberries, hard tannins and residual sweetness.                                               NaN      80   19.0                       California                           Paso Robles      Central Coast                 NaN                   NaN                                                   Vina Robles 2004 Cabernet Sauvignon (Paso Robles)             Cabernet Sauvignon                             Vina Robles
11085        France                                                                                                                                                                                                                                                A white this age should be fresh and crisp; this one is a bit dull and shows only faint bitter lemon flavors on the finish to go with tired apple aromas.                                               NaN      80    8.0                 Southwest France                              Bergerac                NaN      Joe Czerwinski                @JoeCz                                                         Seigneurs de Bergerac 1999 White (Bergerac)                    White Blend                   Seigneurs de Bergerac
11086        France                                                                                                                                                                                                     Picture grandma standing over a pot of stewed prunes, which fill the dusty old house with their sickly aromas. Cooked, earthy and rustic, this wine has little going for it. Just barely acceptable.                                               NaN      80   11.0             Languedoc-Roussillon                                 Fitou                NaN      Joe Czerwinski                @JoeCz                                                                         Mont Tauch 1998 Red (Fitou)                      Red Blend                              Mont Tauch
13025            US                                                                                                                                                                                                                                                                                                Just barely acceptable, this soft, semisweet Cab has Lifesaver candy flavors of cherries and raspberries.                                               NaN      80   28.0                       California                              Monterey      Central Coast                 NaN                   NaN                                                         Pianetta 2004 Cabernet Sauvignon (Monterey)             Cabernet Sauvignon                                Pianetta
13781         Chile                                                                                                                                                                                                                                     Rubbery, animal-like aromas are low on fruit. The palate is shrill and dominated by sharp acidity. Sour, herbal and pinched tasting, this is tart and green overall.                                     Clava Reserve      80   14.0                     Rapel Valley                                   NaN                NaN   Michael Schachner           @wineschach                                                 Quintay 2013 Clava Reserve Carmenère (Rapel Valley)                      Carmenère                                 Quintay
13782         Chile                                                                                                                                                                                                         Yeasty, melony and smelling like yellow mustard, this Moscato is generally unappealing. Spritzy (but barely) on the palate, it has flavors of canned pineapple and mango, with a cloying finish.                                        Left Coast      80    7.0                            Chile                                   NaN                NaN   Michael Schachner           @wineschach                                                              flipflop NV Left Coast Moscato (Chile)                        Moscato                                flipflop
13783         Chile                                                                                                                                                                                                                                                 Strained and oily on the nose, this lacks freshness and fruitiness. Briny flavors are extreme and sweaty, while the finish tastes a lot like sauerkraut.                                           Albamar      80   12.0                Casablanca Valley                                   NaN                NaN   Michael Schachner           @wineschach                                            William Cole 2014 Albamar Chardonnay (Casablanca Valley)                     Chardonnay                            William Cole
14337            US                                                                                                                                                                                                                                                                                        Sweet and sour, with cherry and raspberry jam flavors finished with acidity that stings the palate, like vinegar.                                             Syrah      80   28.0                       California                     Santa Ynez Valley      Central Coast                 NaN                   NaN                                                        Sunstone 2007 Syrah Rosé (Santa Ynez Valley)                           Rosé                                Sunstone
14338            US                                                                                                                                                                                                               Light, almost ephemeral, this pale Pinot does not give you much to hold on to. The fruit is thin to the point of invisible, tasting of watermelon and little else. Thin, watery and plain.                                               NaN      80   28.0                           Oregon                          Rogue Valley    Southern Oregon        Paul Gregutt           @paulgwine                                                               Del Rio 2007 Pinot Noir (Rogue Valley)                     Pinot Noir                                 Del Rio

In [459]:
# reviews.groupby('points').apply(lambda df: df.title.iloc[0]) soon depracated

# group by points and apply a function that returns the title of the first wine in each group

reviews.groupby('points').title.apply(lambda x: x.iloc[0])

points
80     Viña Tarapacá 2015 Gran Reserva Chardonnay (Le...
81     Pura 8 2010 Grand Reserve Pinot Noir (Rapel Va...
82       Mémoires 2015 Rosé (Coteaux Varois en Provence)
83         Koyle 2015 Costa Pinot Noir (Colchagua Costa)
84     Three Brothers 2014 Zero Degree Dry Riesling (...
85     Casa Silva 2008 Gran Reserva Petit Verdot (Col...
86     Clarksburg Wine Company 2010 Chenin Blanc (Cla...
87                     Nicosia 2013 Vulkà Bianco  (Etna)
88                  Fattoria Sardi 2015 Rosato (Toscana)
89           David Fulton 2008 Petite Sirah (St. Helena)
90     Beaumont 2005 Hope Marguerite Chenin Blanc (Wa...
91     Le Riche 2003 Cabernet Sauvignon Reserve Caber...
92     Dopff & Irion 2004 Schoenenbourg Grand Cru Ven...
93     Claiborne & Churchill 2014 Twin Creeks Estate ...
94         Sandeman 2015 Quinta do Seixo Vintage  (Port)
95     Jasper Hill 2013 Georgia's Paddock Shiraz (Hea...
96                        Oremus 2005 Eszencia  (Tokaji)
97     Robert Weil 2014 Kiedrich Gräfenberg Trockenbe...
98     Chambers Rosewood Vineyards NV Rare Muscadelle...
99     Quilceda Creek 2008 Cabernet Sauvignon (Columb...
100    Chambers Rosewood Vineyards NV Rare Muscat (Ru...
Name: title, dtype: object

In [455]:
# reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax(), :])
# This will be depracated
# return the wine with the highest points in each country and province group

idx = reviews.groupby(['country','province']).points.idxmax()
best = reviews.loc[idx,:]

In [456]:
idx

country    province
Argentina  Mendoza Province    82754
           Other               78303
Armenia    Armenia             66146
Australia  Australia Other     37882
           New South Wales     85337
                               ...
Uruguay    Juanico              9133
           Montevideo          15750
           Progreso            93103
           San Jose            39898
           Uruguay             39361
Name: points, Length: 425, dtype: int64

In [454]:
best.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
82754,Argentina,"If the color doesn't tell the full story, the ...",Nicasia Vineyard,97,120.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Bodega Catena Zapata 2006 Nicasia Vineyard Mal...,Malbec,Bodega Catena Zapata
78303,Argentina,"Take note, this could be the best wine Colomé ...",Reserva,95,90.0,Other,Salta,NaN,Michael Schachner,@wineschach,Colomé 2010 Reserva Malbec (Salta),Malbec,Colomé
66146,Armenia,"Deep salmon in color, this wine offers a bouqu...",Estate Bottled,88,15.0,Armenia,NaN,NaN,Mike DeSimone,@worldwineguys,Van Ardi 2015 Estate Bottled Rosé (Armenia),Rosé,Van Ardi
37882,Australia,Writes the book on how to make a wine filled w...,Sarah's Blend,93,15.0,Australia Other,South Eastern Australia,NaN,NaN,NaN,Marquis Philips 2000 Sarah's Blend Red (South ...,Red Blend,Marquis Philips
85337,Australia,De Bortoli's Noble One is as good as ever in 2...,Noble One Bortytis,94,32.0,New South Wales,New South Wales,NaN,Joe Czerwinski,@JoeCz,De Bortoli 2007 Noble One Bortytis Semillon (N...,Sémillon,De Bortoli

### agg() aggregate a bunch of function simultaneously

In [403]:
reviews.groupby(['country']).price.agg([len, min, max]).head() # return a dataframe with count, min, and max price for each country

/tmp/ipykernel_38151/1974734949.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  reviews.groupby(['country']).price.agg([len, min, max]).head() # return a dataframe with count, min, and max price for each country
/tmp/ipykernel_38151/1974734949.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  reviews.groupby(['country']).price.agg([len, min, max]).head() # return a dataframe with count, min, and max price for each country

                         len   min     max
country
Argentina               3800   4.0   230.0
Armenia                    2  14.0    15.0
Australia               2329   5.0   850.0
Austria                 3345   7.0  1100.0
Bosnia and Herzegovina     2  12.0    13.0

### Multi-indexes

        In all of the examples we've seen thus far we've been working with DataFrame or Series objects with a single-label index. groupby() is slightly different in the fact that, depending on the operation we run, it will sometimes result in what is called a multi-index.

        A multi-index differs from a regular index in that it has multiple levels. For example:

In [404]:
countries_reviewed = reviews.groupby(['country', 'province']).description.agg([len])
# return a dataframe with counts of reviews for each country and province combination

🔥 Summary (super simple)

        Grouping by ['country', 'province'] means:

        “Show me every unique combination of country + province found in the dataset.”

        For each combination, you get:

        one row in the output

        a multi-index (country, province)

        one aggregated value per column (here: description.agg(len))

So:

        Argentina + Mendoza Province → one group

        Argentina + Other → another group

        Australia + each province → more groups

In [405]:
countries_reviewed.head(10)

                              len
country   province
Argentina Mendoza Province   3264
          Other               536
Armenia   Armenia               2
Australia Australia Other     245
          New South Wales      85
          South Australia    1349
          Tasmania             42
          Victoria            322
          Western Australia   286
Austria   Austria              26

In [408]:
countries_location = reviews.groupby(['country', 'province'])

In [409]:
for key, df in countries_location:
    print("Group", key)
    print(df.head().to_string())
    break

Group ('Argentina', 'Mendoza Province')
       country                                                                                                                                                                                                                                                                                         description                designation  points  price          province       region_1 region_2        taster_name taster_twitter_handle                                                    title    variety              winery
17   Argentina                                               Raw black-cherry aromas are direct and simple but good. This has a juicy feel that thickens over time, with oak character and extract becoming more apparent. A flavor profile driven by dark-berry fruits and smoldering oak finishes meaty but hot.        Winemaker Selection      87   13.0  Mendoza Province        Mendoza      NaN  Michael Schachner           @wineschach  Gaucho Andino 2011 Winemaker Selection Malbec (Mendoza)     Malbec       Gaucho Andino
224  Argentina                                                                    Blackberry and road-tar aromas are dark and stout. This is moderately tannic and a bit rough and jagged on the palate. Flavors of stewed black plum and prune are ripe almost to an extreme, and that's how it finishes as well.                      Lunta      90   22.0  Mendoza Province  Luján de Cuyo      NaN  Michael Schachner           @wineschach                 Mendel 2014 Lunta Malbec (Luján de Cuyo)     Malbec              Mendel
231  Argentina                                         Meaty and rubbery, but that's young Bonarda. This is a sound wine with dark berry flavors, raisin and pulsing acidity. Still, there's modest roundness to the palate and length to the finish. Overall, it's tasty, full and borderline raisiny. Drink now.                        NaN      85   10.0  Mendoza Province        Mendoza      NaN  Michael Schachner           @wineschach                        Andean Sky 2007 Bonarda (Mendoza)    Bonarda          Andean Sky
253  Argentina  Huge in color and extract, but also a little childish. The nose has gumball, berry jam and a touch of volatility, but after things settle it rests on bold black fruit. It's not overly rich or sweet, and the feel is sort of sinewy. Seems more about size and color than refinement and polish.                    Reserve      85   15.0  Mendoza Province  Luján de Cuyo      NaN  Michael Schachner           @wineschach   Cueva de las Manos 2007 Reserve Malbec (Luján de Cuyo)     Malbec  Cueva de las Manos
261  Argentina                                  A blend of 50% Malbec with Cabernet, Syrah and Merlot that's lightly minty and full of tobacco, pepper and spicy aromas. Feels a bit clampy and tannic, with oaky, herbal flavors of plum and sweet berry. Shows a hint of green and drying tannins on the finish.  Estate Blend Gran Reserva      89   37.0  Mendoza Province            NaN      NaN  Michael Schachner           @wineschach               Algodon 2008 Estate Blend Gran Reserva Red  Red Blend             Algodon

In [410]:
countries_location.get_group(('Argentina', 'Mendoza Province')).head()
# return a dataframe with all reviews from Argentina, Mendoza Province group

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
17,Argentina,Raw black-cherry aromas are direct and simple ...,Winemaker Selection,87,13.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Gaucho Andino 2011 Winemaker Selection Malbec ...,Malbec,Gaucho Andino
224,Argentina,Blackberry and road-tar aromas are dark and st...,Lunta,90,22.0,Mendoza Province,Luján de Cuyo,NaN,Michael Schachner,@wineschach,Mendel 2014 Lunta Malbec (Luján de Cuyo),Malbec,Mendel
231,Argentina,"Meaty and rubbery, but that's young Bonarda. T...",NaN,85,10.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Andean Sky 2007 Bonarda (Mendoza),Bonarda,Andean Sky
253,Argentina,"Huge in color and extract, but also a little c...",Reserve,85,15.0,Mendoza Province,Luján de Cuyo,NaN,Michael Schachner,@wineschach,Cueva de las Manos 2007 Reserve Malbec (Luján ...,Malbec,Cueva de las Manos
261,Argentina,"A blend of 50% Malbec with Cabernet, Syrah and...",Estate Blend Gran Reserva,89,37.0,Mendoza Province,NaN,NaN,Michael Schachner,@wineschach,Algodon 2008 Estate Blend Gran Reserva Red,Red Blend,Algodon

In [411]:
countries_reviewed.index
# this is a multi-index with two levels: 'country' and 'province'
# because we grouped by two columns, the resulting DataFrame has a multi-index with two levels

MultiIndex([('Argentina',  'Mendoza Province'),
            ('Argentina',             'Other'),
            (  'Armenia',           'Armenia'),
            ('Australia',   'Australia Other'),
            ('Australia',   'New South Wales'),
            ('Australia',   'South Australia'),
            ('Australia',          'Tasmania'),
            ('Australia',          'Victoria'),
            ('Australia', 'Western Australia'),
            (  'Austria',           'Austria'),
            ...
            (       'US',        'Washington'),
            (       'US', 'Washington-Oregon'),
            (  'Ukraine',           'Ukraine'),
            (  'Uruguay',         'Atlantida'),
            (  'Uruguay',         'Canelones'),
            (  'Uruguay',           'Juanico'),
            (  'Uruguay',        'Montevideo'),
            (  'Uruguay',          'Progreso'),
            (  'Uruguay',          'San Jose'),
            (  'Uruguay',           'Uruguay')],
           names=['country', 'province'], length=425)

In [412]:
countries_reviewed.head()

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
Armenia   Armenia              2
Australia Australia Other    245
          New South Wales     85

In [413]:
countries_reviewed.reset_index(inplace=True)

### SORTING

In [415]:
countries_reviewed.sort_values(by='len')

          country                  province    len
40         Brazil          Serra do Sudeste      1
63          Chile                   Coelemu      1
354  South Africa                Paardeberg      1
48         Canada              Canada Other      1
58          Chile  Casablanca-Curicó Valley      1
..            ...                       ...    ...
409            US                    Oregon   5373
227         Italy                   Tuscany   5897
118        France                  Bordeaux   5941
415            US                Washington   8639
392            US                California  36247

[425 rows x 3 columns]

In [416]:
countries_reviewed.sort_values(by='len', ascending=False).head(10)

       country          province    len
392         US        California  36247
415         US        Washington   8639
118     France          Bordeaux   5941
227      Italy           Tuscany   5897
409         US            Oregon   5373
119     France          Burgundy   3980
375      Spain    Northern Spain   3851
224      Italy          Piedmont   3729
0    Argentina  Mendoza Province   3264
228      Italy            Veneto   2716

In [417]:
countries_reviewed.sort_index().head(10)

     country           province   len
0  Argentina   Mendoza Province  3264
1  Argentina              Other   536
2    Armenia            Armenia     2
3  Australia    Australia Other   245
4  Australia    New South Wales    85
5  Australia    South Australia  1349
6  Australia           Tasmania    42
7  Australia           Victoria   322
8  Australia  Western Australia   286
9    Austria            Austria    26

In [ ]:
countries_reviewed.sort_values(by=['country', 'len']).head(10)

      country           province   len
1   Argentina              Other   536
0   Argentina   Mendoza Province  3264
2     Armenia            Armenia     2
6   Australia           Tasmania    42
4   Australia    New South Wales    85
3   Australia    Australia Other   245
8   Australia  Western Australia   286
7   Australia           Victoria   322
5   Australia    South Australia  1349
20    Austria      Südburgenland     2

In [238]:
print(reviews.head().to_string())

    country                                                                                                                                                                                                                                                description                         designation  points  price           province             region_1           region_2         taster_name taster_twitter_handle                                                                                title         variety               winery
0     Italy                                                                               Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity.                        Vulkà Bianco      87    NaN  Sicily & Sardinia                 Etna                NaN       Kerin O’Keefe          @kerinokeefe                                                    Nicosia 2013 Vulkà Bianco  (Etna)     White Blend              Nicosia
1  Portugal                        This is ripe and fruity, a wine that is smooth while still structured. Firm tannins are filled out with juicy red berry fruits and freshened with acidity. It's  already drinkable, although it will certainly be better from 2016.                            Avidagos      87   15.0              Douro                  NaN                NaN          Roger Voss            @vossroger                                        Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red  Quinta dos Avidagos
2        US                                                                 Tart and snappy, the flavors of lime flesh and rind dominate. Some green pineapple pokes through, with crisp acidity underscoring the flavors. The wine was all stainless-steel fermented.                                 NaN      87   14.0             Oregon    Willamette Valley  Willamette Valley        Paul Gregutt           @paulgwine                                         Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris            Rainstorm
3        US                                                    Pineapple rind, lemon pith and orange blossom start off the aromas. The palate is a bit more opulent, with notes of honey-drizzled guava and mango giving way to a slightly astringent, semidry finish.                Reserve Late Harvest      87   13.0           Michigan  Lake Michigan Shore                NaN  Alexander Peartree                   NaN                  St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)        Riesling           St. Julian
4        US  Much like the regular bottling from 2012, this comes across as rather rough and tannic, with rustic, earthy, herbal characteristics. Nonetheless, if you think of it as a pleasantly unfussy country wine, it's a good companion to a hearty winter stew.  Vintner's Reserve Wild Child Block      87   65.0             Oregon    Willamette Valley  Willamette Valley        Paul Gregutt           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)      Pinot Noir         Sweet Cheeks

### 1.

        Who are the most common wine reviewers in the dataset? Create a Series whose index is the taster_twitter_handle category from the dataset, and whose values count how many reviews each person wrote.

In [318]:
test = reviews.groupby('taster_twitter_handle')

In [322]:
test.get_group(('@vossroger')).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer
30,France,Red cherry fruit comes laced with light tannin...,Nouveau,86,NaN,Beaujolais,Beaujolais-Villages,NaN,Roger Voss,@vossroger,Domaine de la Madone 2012 Nouveau (Beaujolais...,Gamay,Domaine de la Madone

In [ ]:
test.taster_twitter_handle.count() # return a series with counts of reviews for each taster_twitter_handle

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
Name: taster_twitter_handle, dtype: int64

In [336]:
reviews.groupby('taster_twitter_handle').taster_twitter_handle.count()
# first, group by taster_twitter_handle, then count non-null entries in the taster_twitter_handle column for each group

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
Name: taster_twitter_handle, dtype: int64

In [334]:
for key, df in reviews.groupby('taster_twitter_handle'):
    print(f'Key: {key}')
    print(df.head().to_string())
    break

Key: @AnneInVino
     country                                                                                                                                                                                                                                                                                                                                description      designation  points  price       province region_1 region_2       taster_name taster_twitter_handle                                                     title           variety                 winery
93   Austria                                                                                                                                                   Freshness characterizes the nose: green pear, ivy leaves and citrus notes play on nose and palate. This is light footed, easy drinking and charming. Drink soon while flavors are fresh.              NaN      88   12.0     Burgenland      NaN      NaN  Anne Krebiehl MW           @AnneInVino                  Fuchs 2015 Grüner Veltliner (Burgenland)  Grüner Veltliner                  Fuchs
340   France                                                                                                                                                                                        The nose is muted, despite the slight spritz of the wine, while the palate is equally toned down. It's a rounded if not very expressive white wine.        Tradition      82   18.0         Alsace   Alsace      NaN  Anne Krebiehl MW           @AnneInVino  Antoine Moltès & Fils 2015 Tradition Pinot Gris (Alsace)        Pinot Gris  Antoine Moltès & Fils
423  Austria                                                                                                              There is a savory, fragrant, mossy greenness that draws you in. On the concentrated palate, this becomes more distinct as the peel of Bosc pear and crushed arugula emerge. Lime zestiness comes with a slightly warm finish.            Kittl      89   23.0    Weinviertel      NaN      NaN  Anne Krebiehl MW           @AnneInVino            Kohl 2015 Kittl Grüner Veltliner (Weinviertel)  Grüner Veltliner                   Kohl
428  Austria                                                                                                 An earthy hint colors the pear notes which on the palate acquire a fresh, almost floral quality. The earthy tone of yeast and miso provides a counterpoint to the zesty, lime-peel freshness. The finish is clean-cut and very refreshing.  Crazy Creatures      89   17.0       Kremstal      NaN      NaN  Anne Krebiehl MW           @AnneInVino    Malat 2015 Crazy Creatures Grüner Veltliner (Kremstal)  Grüner Veltliner                  Malat
435  Austria  Creamy notes pear crumble make for a most attractive nose. The palate follows with gentle softness and concentration, supported by bright, fresh acidity. The creamy notes continue alongside notes of green and red apple and fresh pear. There is a lot of substance and body, so have this alongside a meal, the finish is superclean.      Lage Modler      89    NaN  Thermenregion      NaN      NaN  Anne Krebiehl MW           @AnneInVino   Gebeshuber 2015 Lage Modler Zierfandler (Thermenregion)       Zierfandler             Gebeshuber

### 2.
        What is the best wine I can buy for a given amount of money? Create a Series whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending (so that 4.0 dollars is at the top and 3300.0 dollars is at the bottom).

In [359]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [360]:
test = reviews.groupby('price')

In [363]:
test.get_group(15.0).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
36,Chile,"White flower, lychee and apple aromas carry th...",Estate,86,15.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Estampa 2011 Estate Viognier-Chardonnay (Colch...,Viognier-Chardonnay,Estampa
53,France,"Fruity and lightly herbaceous, this has fine t...",La Fleur d'Amélie,85,15.0,Bordeaux,Bordeaux Blanc,NaN,Roger Voss,@vossroger,Château de Sours 2011 La Fleur d'Amélie (Bord...,Bordeaux-style White Blend,Château de Sours
66,France,"This soft, rounded wine is ripe with generous ...",NaN,86,15.0,Burgundy,Mâcon-Milly Lamartine,NaN,Roger Voss,@vossroger,Vignerons des Terres Secrètes 2015 Mâcon-Mill...,Chardonnay,Vignerons des Terres Secrètes

In [378]:
reviews.groupby('price').points.max().sort_index()

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

### 3.
        What are the minimum and maximum prices for each variety of wine? Create a DataFrame whose index is the variety category from the dataset and whose values are the min and max values thereof.

In [ ]:
reviews.groupby('variety').agg({'points': 'sum', 'price': 'max',})
# return a DataFrame with total points and max price for each variety

             points  price
variety
Abouriou        263   75.0
Agiorgitiko    5483   66.0
Aglianico     32050  180.0
Aidani           82   27.0
Airen           245   10.0
...             ...    ...
Zinfandel    238367  100.0
Zlahtina        172   16.0
Zweigelt      18454   70.0
Çalkarası       173   19.0
Žilavka          88   15.0

[707 rows x 2 columns]

In [ ]:
reviews.groupby('variety').agg(
    points_sum = ('points', 'sum'),
    price_min = ('price', 'min'),
    price_max= ('price', 'max') 
)
# returns a DataFrame with a MultiIndex column 
# for price (min,max)

             points_sum  price_min  price_max
variety
Abouriou            263       15.0       75.0
Agiorgitiko        5483       10.0       66.0
Aglianico         32050        6.0      180.0
Aidani               82       27.0       27.0
Airen               245        8.0       10.0
...                 ...        ...        ...
Zinfandel        238367        5.0      100.0
Zlahtina            172       13.0       16.0
Zweigelt          18454        9.0       70.0
Çalkarası           173       19.0       19.0
Žilavka              88       15.0       15.0

[707 rows x 3 columns]

In [ ]:
reviews.groupby('variety').price.agg(['min', 'max'])
# returns a DataFrame with a MultiIndex column for price (min,max)

              min    max
variety
Abouriou     15.0   75.0
Agiorgitiko  10.0   66.0
Aglianico     6.0  180.0
Aidani       27.0   27.0
Airen         8.0   10.0
...           ...    ...
Zinfandel     5.0  100.0
Zlahtina     13.0   16.0
Zweigelt      9.0   70.0
Çalkarası    19.0   19.0
Žilavka      15.0   15.0

[707 rows x 2 columns]

### 4.
        What are the most expensive wine varieties? Create a variable `sorted_varieties` containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).

In [474]:
reviews.groupby('variety').price.agg(['min', 'max']).sort_values(by=['min', 'max'], ascending=False)

                                  min    max
variety
Ramisco                         495.0  495.0
Terrantez                       236.0  236.0
Francisa                        160.0  160.0
Rosenmuskateller                150.0  150.0
Tinta Negra Mole                112.0  112.0
...                               ...    ...
Roscetto                          NaN    NaN
Sauvignon Blanc-Sauvignon Gris    NaN    NaN
Tempranillo-Malbec                NaN    NaN
Vital                             NaN    NaN
Zelen                             NaN    NaN

[707 rows x 2 columns]

## 5.
Create a `Series` whose index is reviewers and whose values is the average review score given out by that reviewer. Hint: you will need the `taster_name` and `points` columns.

In [ ]:
test = reviews.groupby('taster_name').points
# return a series with taster_name as index and points as values

In [ ]:
test.get_group('Roger Voss')
# retrieve all points reviews by taster 'Roger Voss'

1         87
7         87
9         87
11        87
30        86
          ..
129964    90
129965    90
129968    90
129969    90
129970    90
Name: points, Length: 25514, dtype: int64

In [ ]:
test.groups.keys()
# return the list of taster names (group keys)

dict_keys(['Alexander Peartree', 'Anna Lee C. Iijima', 'Anne Krebiehl\xa0MW', 'Carrie Dykes', 'Christina Pickard', 'Fiona Adams', 'Jeff Jenssen', 'Jim Gordon', 'Joe Czerwinski', 'Kerin O’Keefe', 'Lauren Buzzeo', 'Matt Kettmann', 'Michael Schachner', 'Mike DeSimone', 'Paul Gregutt', 'Roger Voss', 'Sean P. Sullivan', 'Susan Kostrzewa', 'Virginie Boone'])

In [ ]:
reviews.groupby('taster_name').points.mean()
# return the mean points for each taster_name group

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
Anne Krebiehl MW      90.562551
Carrie Dykes          86.395683
Christina Pickard     87.833333
Fiona Adams           86.888889
Jeff Jenssen          88.319756
Jim Gordon            88.626287
Joe Czerwinski        88.536235
Kerin O’Keefe         88.867947
Lauren Buzzeo         87.739510
Matt Kettmann         90.008686
Michael Schachner     86.907493
Mike DeSimone         89.101167
Paul Gregutt          89.082564
Roger Voss            88.708003
Sean P. Sullivan      88.755739
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, dtype: float64

In [ ]:
reviews.groupby('taster_name').points.mean().describe()
# describe the statistical summary of the mean points for each taster_name group

count    19.000000
mean     88.233026
std       1.243610
min      85.855422
25%      87.323501
50%      88.536235
75%      88.975256
max      90.562551
Name: points, dtype: float64

### 6.
        What combination of countries and varieties are most common? Create a `Series` whose index is a `MultiIndex`of `{country, variety}` pairs. For example, a pinot noir produced in the US should map to `{"US", "Pinot Noir"}`. Sort the values in the `Series` in descending order based on wine count.

In [557]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [666]:
test = reviews.groupby(['country', 'variety'])

In [667]:
test.get_group(('US', 'Pinot Noir')).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
21,US,"A sleek mix of tart berry, stem and herb, alon...",NaN,87,20.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Acrobat 2013 Pinot Noir (Oregon),Pinot Noir,Acrobat
25,US,Oak and earth intermingle around robust aromas...,King Ridge Vineyard,87,69.0,California,Sonoma Coast,Sonoma,Virginie Boone,@vboone,Castello di Amorosa 2011 King Ridge Vineyard P...,Pinot Noir,Castello di Amorosa
35,US,As with many of the Erath 2010 vineyard design...,Hyland,86,50.0,Oregon,McMinnville,Willamette Valley,Paul Gregutt,@paulgwine,Erath 2010 Hyland Pinot Noir (McMinnville),Pinot Noir,Erath
41,US,"A stiff, tannic wine, this slowly opens and br...",NaN,86,22.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Hawkins Cellars 2009 Pinot Noir (Willamette Va...,Pinot Noir,Hawkins Cellars

In [ ]:
reviews.groupby(['country', 'variety']).size().sort_values(ascending=False)
# return a series with MultiIndex (country, variety) and counts of reviews for each combination

country    variety
Argentina  Barbera                         1
           Bonarda                       105
           Bordeaux-style Red Blend       89
           Bordeaux-style White Blend      1
           Cabernet Blend                  8
                                        ...
Uruguay    Tannat-Cabernet Franc           2
           Tannat-Merlot                   6
           Tannat-Syrah                    1
           Tempranillo-Tannat              1
           White Blend                     1
Length: 1612, dtype: int64

In [725]:
print(sf)

   index    Stock   Price Location ETF  Valid  Shares
0      0   Google   320.0      CAN   Y      9     421
1      1     META   399.0      SEB   Y      8     194
2      2   TIKTAK   432.0      KOR   Y      7     212
3      3   OpenAI   482.0     CHIL   N      6     123
4      4      HNG   732.0      CHI   Y      5     283
5      5  Celsius   883.0      UAE   N      4      93
6      6    Alani   883.0      PHI   Y      3      93
7      7    Apple  1010.0      USA   Y      2     139
8      8      XKJ     NaN      JAP   N      1     333

In [ ]:
sf.shape # return 9 rows, 7 columns

(9, 7)

In [728]:
sf.shape[0] # return number of rows

9

In [729]:
sf.shape[1] # return number of columns

7

In [730]:
sf.size # return total number of elements (rows * columns) = 63

63